### ISSUE TITLE
port 24800 is blocked in the switch, how can i use different port (MacOS - Big Sur)

### ISSUE THREAD

**Issue by amjadqzz1997** [debauchee/barrier#1049]
connection timeout, since port 24800 is blocked, and i would like to use instead port 1025.
i cannot change the switch settings, iam not Admin
is there any way change the port, thanks
Barrier gonna simplify my life... please help on that.

**Comment by albertony** [comment]
On server: Menu `Barrier` > `Change Settings`, set the port you want under the `Networking` section.
On client: Set port number following a `:` after the `server IP`, e.g. `192.168.0.99:1025` (where the example IP `192.168.0.99` of course must be changed to the address of your actual server).

**Comment by amjadqzz1997** [comment]
Hello @albertony ,

Thank u for the quick reply, i could not find the networking section, please see the below picture,
please let me know what menu are u taking about, can us send me a screen shot ?

Your assistance is highly appreciated,

Best regards,
Amjad Abu Aisha

![Uploading Bildschirmfoto 2021-02-03 um 17.39.32.png…]()

**Comment by albertony** [comment]
Oh sorry, looks different on MacOS than on Windows. Try F4 key.

**Comment by p12tic** [comment]
I'm closing this issue as it seems the last comment has answered the question. If this is not the case, please re-open.

**Comment by tallero** [comment]
How to set the port in the configuration file/command line?

**Comment by albertony** [comment]
On server, you set the port as part of the `-a, --address <address>` option. See: 
https://github.com/debauchee/barrier/wiki/Command-Line#server-command-line-options

E.g for port 1234, some alternatives are:
--address :1234
--address 0.0.0.0:1234
--address localhost:1234
