### ISSUE TITLE
Switch screens using shortcut.

### ISSUE THREAD

**Issue by gryf** [debauchee/barrier#1064]
I'm wondering, is it possible to switch between the screens using some defined keyboard shortcut rather than moving the mouse?

**Comment by cryzed** [comment]
Yes, just check the "Hotkeys" tab under "Configure Server".

**Comment by imtbl** [comment]
Yes, you can configure them in `Server configuration` -> `Hotkeys`. E.g.:

![image](https://user-images.githubusercontent.com/28833155/108005550-4e87e200-6ff9-11eb-8f1d-a984ca62a391.png)

**Comment by gryf** [comment]
thanks!

**Comment by rish15** [comment]
where do you get the functionName? 
suppose I want to switch from my server over to client ?
