### ISSUE TITLE
Barrier incompatibility with certain Microsoft programs?

### ISSUE THREAD

**Issue by DwertlePlayz** [debauchee/barrier#1103]
While having barrier open, it seems to be cutting off internet to other programs on my computer. Some of these include Microsoft Word, Teams, Outlook, and Onenote. After closing barrier and restarting the programs they all begin to work fine again.

While having barrier open with these programs active it cannot connect to other clients. When these programs are not running barrier is working as expected. 

Do you guys know why this is happening?

**Comment by p12tic** [comment]
@DwertlePlayz I'm wondering why did you close the issue, Did you find what was wrong?
