### ISSUE TITLE
GESTURES: FEATURE REQUEST! 

### ISSUE THREAD

**Issue by iknowzo** [debauchee/barrier#114]
Magic Trackpad gestures do not work on controlling the second mac. I've tried resetting trackpad settings on both devices but that didn't help. Can you please please add this feature? 

Running on MacOS 10.14 Beta (18A365a)

### Barrier Version ###

1.9.π

**Comment by walker0643** [comment]
This is a tall order given that I don't have a trackpad (or a Mac at the moment). I also don't see it being a widely-used feature. Sorry :)

**Comment by johndbritton** [comment]
@walker0643 I would really love to have this feature as well. Any idea how hard it would be to implement? Maybe you can provide some suggestions on how it could be added?

**Comment by rumym** [comment]
Would like to see this feature as well if it is still being considered

**Comment by moeffju** [comment]
It was a big thing in synergy and it’s definitely painful when using multiple Macs: https://github.com/symless/synergy-core/issues/2905

**Comment by program-om** [comment]
Please support this feature ASAP! Scrolling up and down with the trackpad seems to work though!
