### ISSUE TITLE
Running `barriers` instead of the barrier GUI makes it not work

### ISSUE THREAD

**Issue by clyde37** [debauchee/barrier#1153]
**Describe the bug**
When I run the headless barrier server instead of the qt GUI for it, it prints
```
NOTE: new client is unresponsive
NOTE: accepted client connection
```
over and over and it doesn't work.

Possibly related: #789

**To Reproduce**
Run `barriers` instead of `barrier`

Server: Archlinux
Barrier 2.3.3-1
Client: Windows 10
Barrier 2.3.3-release-3395cca9

My desktop is connected to Ethernet and my laptop is connected to Wi-Fi, both are using 192.168 addresses

Log with no useful information
[barriers.log](https://github.com/debauchee/barrier/files/6410621/barriers.log)
barrier.conf renamed to have txt on the end because for some reason GitHub doesn't let you upload certain file extensions
[barrier.conf.txt](https://github.com/debauchee/barrier/files/6410628/barrier.conf.txt)

**Comment by lededev** [comment]
This is my headless solution, I am still using.
https://github.com/debauchee/barrier/issues/1135

**Comment by lededev** [comment]
and PR https://github.com/debauchee/barrier/pull/1139 you can compile both Archlinux and windows 10.

**Comment by clyde37** [comment]
That's not why it wasn't working, presumably there was something wrong with the way my network was configured. It's working now.
