### ISSUE TITLE
Trying to make a hotkey for Ctrl to Cmd on PC|Mac build.

### ISSUE THREAD

**Issue by Uzukii** [debauchee/barrier#1163]
I want to be able to copy and paste in Mac OS with the same keys you do in Windows (Ctrl+C, Ctrl+V). The problem is Mac uses Cmd+C, Cmd+V and Windows doesn't have a Cmd key. It has the Win key in it's place. And the Win key can't be used as a modifier key in Barrier. So I can't make a Ctrl = Win or Ctrl+C, Ctrl+V = Cmd(Win)+C, Cmd(Win)+V hotkey.

**Comment by serek2298** [comment]
Its working this way by deafult in my case. Simply enable clipboard sharing.

**Comment by lededev** [comment]
You need read wiki.
https://github.com/debauchee/barrier/wiki/Command-Line#server_config

shift, ctrl, alt, altgr, meta, and super allow these keys to be mapped to a different key for that screen.

**Comment by Uzukii** [comment]
> You need read wiki.
> https://github.com/debauchee/barrier/wiki/Command-Line#server_config
> 
> shift, ctrl, alt, altgr, meta, and super allow these keys to be mapped to a different key for that screen.

Sorry, but I don't know what I'm looking at here. Where in the wiki does it tell you how to map the Ctrl key to the Cmd ⌘ key in Mac OS?

I know there's a way to remap keys in Mac OS itself but that doesn't work with keyboards connected through Barrier.

**Comment by jbg** [comment]
@Uzukii just below the section linked to above you will find https://github.com/debauchee/barrier/wiki/Command-Line#screen-options which shows how to solve your problem. "shift, ctrl, alt, altgr, meta, and super allow these keys to be mapped to a different key for that screen" -- I believe the cmd/windows key is `meta` but try it out and see.

**Comment by owlwoopyto** [comment]
@Uzukii I had this same question. In the server configuration settings, for my Mac client I set the Ctrl: modifier key to Super. Now when I press Ctrl+C on my keyboard, it copies text on the Mac. Hope this helps.

**Comment by YiannisDermitzakis** [comment]
@Uzukii 
You need to create a configuration file and set the remapping there. What @owlwoopyto suggests is something like:

`# C:/Users/<your-user>/barrier.sgc

section: screens
    WindowsPc:
    MacBook-Pro.local:
        # this maps ctrl on the Windows keyboard to super (=command) on the Mac
        ctrl = super
end
section: links
    WindowsPc:
        right = MacBook-Pro.local
    MacBook-Pro.local:
        left = WindowsPc
end`

**Comment by Uzukii** [comment]
> @Uzukii I had this same question. In the server configuration settings, for my Mac client I set the Ctrl: modifier key to Super. Now when I press Ctrl+C on my keyboard, it copies text on the Mac. Hope this helps.

> @Uzukii You need to create a configuration file and set the remapping there. What @owlwoopyto suggests is something like:
> 
> ```
> # C:/Users/<your-user>/barrier.sgc
> 
> section: screens
>     WindowsPc:
>     MacBook-Pro.local:
>         # this maps ctrl on the Windows keyboard to super (=command) on the Mac
>         ctrl = super
> end
> section: links
>     WindowsPc:
>         right = MacBook-Pro.local
>     MacBook-Pro.local:
>         left = WindowsPc
> end
> ```

I can't believe this. When I read owlwoopyto comment I didn't know what he was talking about. It wasn't until after I read YiannisDermitzakis comment about making a configuration file that I realized something. You can **double click** the icons under the Screens and links tab in the Configure Server window.. *facepalm* It's the same as making a configuration file. Thanks guys. I'm going to go bang my head against a wall now.

**Comment by Fauzdar1** [comment]
> 

Strange Enough, with custom config, Client never starts and stuck on Starting in Mac, it works without custom config. Seems like I've to suffer with this Ctrl Command mess.

**Comment by Camble** [comment]
@Fauzdar1 You can change the modifier keys without creating a custom config file. Just open the screen settings in the GUI and select from the dropdowns.

**Comment by MMShep97** [comment]
I'd like to link this comment on a related issue on mapping windows -> mac keys as I spent more than I would've preferred searching for this: https://github.com/debauchee/barrier/issues/201#issuecomment-448074872

**Comment by nbolton** [comment]
Please try Deskflow or Input Leap as Barrier is no longer in development.

https://github.com/deskflow/deskflow
https://github.com/input-leap/input-leap

Both are compatible with Barrier client/server so you can try on one of your computers.

If this is still an issue in those projects, we would appreciate a cross-post of this issue.
