### ISSUE TITLE
Build from sources : Missing header: dns_sd.h

### ISSUE THREAD

**Issue by yesi** [debauchee/barrier#120]
### Operating Systems ###

Gentoo

### Barrier Version ###

2.1.1

### Steps to reproduce bug ###

Install from **emerge** from **pixlra**
https://gpo.zugaina.org/x11-misc/barrier
Without qt5 and libressl support : 
[ebuild  N    ~] x11-misc/barrier-2.1.1::pixlra  USE="-libressl -qt5"

Here's the bug :

CMake Error at CMakeLists.txt:191 (message):
  Missing header: dns_sd.h

### Other info ###
If i understand the issue #52, dns_sd.h should not be needed, right ?

**Comment by AdrianKoshka** [comment]
It shouldn't be needed if you're not building the GUI.

**Comment by jfmcarreira** [comment]
I updated the ebuild to the new version and worked with and without qt5 use flag

**Comment by RealKelsar** [comment]
Hi,
i probably stole parts of that ebuild and made a new one. But just disabling GUI didn't do the trick for me. I added a small patch to make it work.
#473

**Comment by AdrianKoshka** [comment]
#473 was merged, issue _should_ be fixed now.
