### ISSUE TITLE
Cant suspend Windows client

### ISSUE THREAD

**Issue by lucas-gaitzsch** [debauchee/barrier#124]
My Windows Client (connected with LAN) can not suspend if it is connected to the server. It uses the Modern Standby (S0i3).

It is possible to run the Windows Barrier client as User Application and not as service with System-Permissions?

### Operating Systems ###

Server: Arch Linux (4.18.5)

Client: Windows 10 (10.0.17134)

### Barrier Version ###

2.1.0

**Comment by walker0643** [comment]
Yes, it is possible. First I would try opening the Barrier GUI settings and setting Elevate to Never. If that doesn't work then you can run the client manually without the GUI and service wrapper. First stop and disable the service, then open a command prompt and find your installation folder. Type "barrierc --help" and figure out which parameters you want to add. At minimum you'll need something like this:

barrierc --name <client_screen_name> [--enable-crypto] <server_ip_or_hostname>:24800

Let me know how it goes. Thanks :)

**Comment by Lucas-M-G** [comment]
Thank you, it works!
