### ISSUE TITLE
[question] next release?

### ISSUE THREAD

**Issue by leonjza** [debauchee/barrier#1262]
Hello!

First of all, thanks so much for this software! It is incredibly useful!

I wanted to know, when is the next tagged release planned? I noticed it has been over a year since v2.3.3 with 187 commits since.

Thanks!

**Comment by shymega** [comment]
Good point/question. Thank you for the praise. I would agree we need another release. I'm not sure what type of release we should make in terms of versioning. I can collate the changes, and write a proper release notice/update changelog though. Will also need to address any bugs and PRs that can be snuck into the release. What do you think, @p12tic - time for a release?
