### ISSUE TITLE
[feature] Confirm clients from server

### ISSUE THREAD

**Issue by Aposhian** [debauchee/barrier#1263]
Currently, when you join as a client, there is a dialog box to confirm that the server SSL signature matches.

It would be nice to use a similar mechanism to confirm clients joining from the server. This would be a simple way to prevent random clients from joining your server and stealing your keystrokes.

**Comment by DhruvaSambrani** [comment]
Random clients cannot join your server iiuc as you need to configure clients in the "Configure server" tab

**Comment by Aposhian** [comment]
Ok, that's right.
