### ISSUE TITLE
assert.h not found

### ISSUE THREAD

**Issue by rizkyarlin** [debauchee/barrier#128]
### Operating Systems ###

Server: Mac OS High Sierra

Client: Raspbian

I tried to build barrier on my machine and I got this error:

`/Users/rizkyarlin/barrier/src/./lib/common/common.h:47:10: fatal error: 
      'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [src/lib/arch/CMakeFiles/arch.dir/Arch.cpp.o] Error 1
make[1]: *** [src/lib/arch/CMakeFiles/arch.dir/all] Error 2
make: *** [all] Error 2`

**Comment by walker0643** [comment]
@AdrianKoshka - do we have a "Building on Mac" page you could link here for @rizkyarlin?

**Comment by AdrianKoshka** [comment]
Nope, I know nothing about the build process for macOS. If someone wants to clue me in, I could add a page to the wiki,

**Comment by pciavald** [comment]
same error here on macos 10.13, it seems xcode moved their headers in newer versions... 

https://stackoverflow.com/questions/45834148/how-to-compile-synergy-on-mac-new-toolchain-from-2017

**Comment by p12tic** [comment]
Hey, how are you building barrier? Just doing `./clean_build.sh` should be enough. I've rebuilt barrier on all of 10.12, 10.13 and 10.14 and saw no issues. Could it be that you're using cmake and make directly? This approach is not supported.

**Comment by p12tic** [comment]
@rizkyarlin: Ping :-)

**Comment by p12tic** [comment]
I don't have the `Edit` and `New Page` buttons. Looks like there's some kind of permission problem. @walker0643 ?

**Comment by pciavald** [comment]
Sorry i'm out of home for the weekend i'll try it using ./clean_install.sh when i come home.

**Comment by rizkyarlin** [comment]
> @rizkyarlin: Ping :-)

Should I close this issue? I stopped trying to build Barrier on my mac since I found another solution to my problem.

**Comment by kmatt** [comment]
```
diff --git a/clean_build.sh b/clean_build.sh
index fc1065a..5fa1a09 100755
--- a/clean_build.sh
+++ b/clean_build.sh
@@ -14,7 +14,7 @@ if [ "$(uname)" = "Darwin" ]; then
     # OSX needs a lot of extra help, poor thing
     # run the osx_environment.sh script to fix paths
     . ./osx_environment.sh
-    B_CMAKE_FLAGS="-DCMAKE_OSX_SYSROOT=$(xcode-select --print-path)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 $B_CMAKE_FLAGS"
+    B_CMAKE_FLAGS="-DCMAKE_OSX_SYSROOT=$(xcode-select --print-path)/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 $B_CMAKE_FLAGS"
 fi
 # allow local customizations to build environment
 [ -r ./build_env.sh ] && . ./build_env.sh
```
