### ISSUE TITLE
Barrier stopped working on macOS Catalina; assistive devices does not trust this process

### ISSUE THREAD

**Issue by Realinho** [debauchee/barrier#1322]
### What happened?

Hello all,

Have been using Barrier for several months with no issues whatsoever, other than some difficulties getting some hotkey combinations to work (which I'm positive is related to the OS itself and not Barrier).

As of a few weeks ago, if I remember correctly right after a macOS update, Barrier stopped working. It launches successfully but keeps bouncing on the dock every half-second. Checking the log I notice that it's going through some sort of loop related to privacy settings.
I can confirm that I have added Barrier to the Accessibility and Input Monitoring sections under the Privacy tab of System Settings. Tried removing the entries and re-adding them, to no avail. Is it possible that it's looking for something else? 

### Version

v2.3.3

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Catalina (10.15.7)

### Relevant log output

```shell
[2021-10-18T12:03:46] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.
[2021-10-18T12:03:46] ERROR: process exited with error code: 1
[2021-10-18T12:03:46] INFO: detected process not running, auto restarting
```

**Comment by Realinho** [comment]
This seems to have been fixed with the 2.4.0 version

**Comment by halfflat** [comment]
I am getting the same error with v2.4.0 (built from source) under macOS Monterey 12.1. I've confirmed that Barrier has been granted Accessibility permission in the Security&Privacy dialog.

**Comment by halfflat** [comment]
Update: adding `/Applications/Barrier.app/Contents/MacOS/barrier`, `/Applications/Barrier.app/Contents/MacOS/barrierc`, and `/Applications/Barrier.app/Contents/MacOS/barriers` manually to the permitted applications under Accessibility was sufficient; adding just the application `Barrier` was insufficient.

**Comment by francotseng** [comment]
> Update: adding `/Applications/Barrier.app/Contents/MacOS/barrier`, `/Applications/Barrier.app/Contents/MacOS/barrierc`, and `/Applications/Barrier.app/Contents/MacOS/barriers` manually to the permitted applications under Accessibility was sufficient; adding just the application `Barrier` was insufficient.

How to manually add them as allowed applications? Because I can't open the `/Applications/Barrier.app/Contents/MacOS` directory in the interface

**Comment by wallneradam** [comment]
> > Update: adding `/Applications/Barrier.app/Contents/MacOS/barrier`, `/Applications/Barrier.app/Contents/MacOS/barrierc`, and `/Applications/Barrier.app/Contents/MacOS/barriers` manually to the permitted applications under Accessibility was sufficient; adding just the application `Barrier` was insufficient.
> 
> How to manually add them as allowed applications? Because I can't open the `/Applications/Barrier.app/Contents/MacOS` directory in the interface

It is an old question, but my answer may help others. Simply frag and frop barrier from `/Applications/Barrier.app/Contents/MacOS/barrier` . It was enough for me.

**Comment by facundopadilla** [comment]
Hello! I had the same issue. With InputLeap, I can't connect my other desktop to my MacBook, so:

1. Drag and drop the Barrier app to the desktop.
2. Allow accessibility permissions.
3. Create the SSL certificate, check it here: https://github.com/debauchee/barrier/issues/1609#issuecomment-1066938159.
4. On your server (Mac), configure it by adding a new device (make sure the client device added to your Mac has the same name).
5. On your client (in my case, Windows), enable SSL connection in Barrier -> Change Settings -> Enable SSL, click the OK button, and activate the "Auto config" checkbox.
6. Enjoy!
