### ISSUE TITLE
Feature request: Always show cursor

### ISSUE THREAD

**Issue by shymega** [debauchee/barrier#1397]
### Discussed in https://github.com/debauchee/barrier/discussions/1392

<div type='discussions-op-text'>

<sup>Originally posted by **hiuwo** June 20, 2020</sup>
I would like to request a feature to **not hide cursors**, either a toggle for all barrier processes, or even better individual toggles for each client/server.

It seems that hiding is great as a presentation and a visual indicator, but say if I have a dedicated trackpad also for the client which is a laptop, it would not be allowed to work properly, (unless the user think of a way to trick the system, for instance on a mac client you would need to guess and move the cursor to the top of the screen and click the menu bar once to reveal it)

(I am also guessing the hiding cursor may be a case of creating a phantom screen space for the cursor to lie in or something which can cause other bugs with windows or cursor management apps)</div>

**Comment by p12tic** [comment]
I've deleted the discussion and reopened https://github.com/debauchee/barrier/issues/760

**Comment by shymega** [comment]
OK. Closing.
