### ISSUE TITLE
Client Stuck on "Barrier is starting"

### ISSUE THREAD

**Issue by jhox616** [debauchee/barrier#1437]
### What happened?

I have disable my firewall, started the barrier server on my Windows 10 machine, and also the client barrier on my linux laptop.
They are connected via Ethernet cable through the router.
It seems to be hanging here but I'm not sure what is causing it to fail. . . 
I configured the server with using the same names as my devices.

* I have x3 monitors on my Windows machine (not sure if that could be causing it)

Any help would be greatly appreciated.

### Version

v2.3.3

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Windows 10
Zorin 16 Pro

**Comment by luochen1990** [comment]
I have similar issue, how do you fix it?
