### ISSUE TITLE
Windows 10 scaling not supported under certain circumstances

### ISSUE THREAD

**Issue by sgrienen** [debauchee/barrier#1462]
### What happened?

When my Win 10 PC (server, on the left side) is configured to scale to 125%, I cannot use it as a server together with my Mac (client on the right side), because when it moves from one to the other, when arriving to 3/4 of the PC screen, it immediately jumps to the bottom right corner of the Mac and makes the whole sharing useless until I disable the client on the Mac. As soon as I switch to 100% scaling, everything's ok again. So what I did is downgraded the PC to 2.3.4, and it seems to be working fine again, as it was for more than a year with 2.3.3.

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Windows, macOS

### What OS versions are you using?

Server 10.0.19042.1348
Client Monterey 12.0.1

**Comment by vvuk** [comment]
Same issue -- 2.4.0 is broken for me under Windows 11.  Main monitor (server) at 150%.  Mouse jumps to adjacent barrier screen at wrong location and can never come back.  2.3.4 fixes things.

**Comment by okihus** [comment]
Im experiencing same issue with 150% scalling on windows using 2.4.0

**Comment by mrwensveen** [comment]
This looks like a regression (#304). The file that fixed this issue is deleted in the current version.

**Comment by danielponte** [comment]
Same issue here, please fix :)
