### ISSUE TITLE
Amazing job! @ didnt work for me

### ISSUE THREAD

**Issue by Askmewho** [debauchee/barrier#149]
### Operating Systems ###

Server: Raspbian

Client: Windows 7

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

Everything works has expected except than alt gr + 2 on my latinoamerican keyboard doesn't work.
on raspbian the results its @ and on windows its just 2. the same I tried with alt gr + Q letter.
maybe its a silly thing. I am extremely suppressed of your work, different hardware (ARM!) and os's, even clipboard work, this its insane guys.

**Comment by gelldur** [comment]
Same on Ubuntu 14.04 and Arch
