### ISSUE TITLE
my windows client screen is active all the time (avoid energy settings)

### ISSUE THREAD

**Issue by Askmewho** [debauchee/barrier#151]
Operating Systems

Server: Raspbian

Client: Windows 7

Barrier Version
2.1.0

Steps to reproduce bug

its on the title. how to enable power saving on the client window? Its a silly question, but I use my pc on all the time, so I dont like it with the screen on all the time. Thanks to everything

**Comment by AdrianKoshka** [comment]
Did you resolve your issue? If-so, it might be nice to say how you did, so that others who might stumble upon this issue might find said solution.
