### ISSUE TITLE
Debug Builds seemingly don't work on Windows?

### ISSUE THREAD

**Issue by AdrianKoshka** [debauchee/barrier#153]
### Operating Systems ###

Build System: Windows 10 1809

### Barrier Version ###

master

### Steps to reproduce bug ###

1. Clone barrier repo
2. Follow [Building on Windows](https://github.com/debauchee/barrier/wiki/Building-on-Windows)
3. Notice `clean_build.bat` doesn't seem to work, unless `Debug` is changed to `Release`

**Comment by AdrianKoshka** [comment]
False alarm, `Debug` seems to work now?

**Comment by gelldur** [comment]
CircleCI has free plan with Windows build ;)
