### ISSUE TITLE
Linux Server -> Windows client, mouse only passes to client through the left side

### ISSUE THREAD

**Issue by ChatAround-Dev** [debauchee/barrier#1566]
### What happened?

Version: 2.4.0 (though the same behavior occurs on version 2.3.2 )
Server: Ubuntu 21.10
Client: Windows 11

Client can connect fine (it show on the logs), but the mouse only passes to client if I configure the client to be on the left position. On any other position (up, right, down, or any corner), the mouse doesn't pass through.

On another Windows 11 server, it works as expected.

Some backstory on the issue:
I was having some non-related mouse sticking issues after I've updated to Windows 11, and I tried to uninstall both Client and Server versions of Barrier and it's config files, tried a bunch of versions, couldn't get it to work, until I've noticed it would work if i put the client on the left position. It is usable, the mouse sticking issue is gone, but no other client position works beside the very left.

### Version

v2.4.0

### If applicable, where did you install Barrier from?

Ubuntu official 2.4.0 deb file, Windows bin release.

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### What OS versions are you using?

Ubuntu 21.10 - Gnome
Windows 11

### Relevant log output

```shell
The following info only appears when setting the client to the left position
[2022-02-14T23:03:01] INFO: switch from "PC-1" to "PC-2" at 1535,479
[2022-02-14T23:03:01] INFO: leaving screen
[2022-02-14T23:03:05] INFO: switch from "PC-2" to "PC-1" at 6,531
[2022-02-14T23:03:05] INFO: entering screen
```

**Comment by ChatAround-Dev** [comment]
Ok, the issue was not as reproducible as I thought. But as soon as I've tried disabling Wayland on ubuntu, it started working again. I actually forgot that I setup Wayland to do some tests and forgot to disable it, and I'm pretty sure the issue started when I started using it. It seems fixed to me.

As a suggestion, some kind of warning if Wayland is detected on a Linux system would probably save hours of debugging.

**Comment by gurupras** [comment]
I think there _is_ an issue here.. or at least, something that I don't fully understand.

I'm facing the same issue with Ubuntu 22.04 (server) running Wayland and Windows 11 (client). Oddly, mouse passes  to the client successfully only through left side. On the right side, it's hit or miss. If I keep pushing the mouse sufficiently through the right and top corners, eventually the mouse does pass through, but until then, I can see it flickering between center and left corner on Windows (client).

FWIW, I have a two-monitor setup in Ubuntu and.. moving the mouse from my left monitor moves it into the right monitor. In case it matters, my left monitor on Ubuntu is my primary monitor, (1), and the right monitor is (2).
