### ISSUE TITLE
unable to change hostname

### ISSUE THREAD

**Issue by ma3252788** [debauchee/barrier#1588]
### What happened?

I cannot modify the hostname of the client, even if I have modified the name of the machine in the computer properties.

Win11

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Windows

### What OS versions are you using?

Win11

**Comment by ma3252788** [comment]
Because the name used on my original computer contains Chinese, I can't connect. So I want to change the hostname to English, but I can't.

**Comment by sabarnix** [comment]
how did you resolve this?
