### ISSUE TITLE
Log shows "entering screen" on clients but the display stays in server screen; moving mouse back into server display and log shows "Entering screen"

### ISSUE THREAD

**Issue by 54bvc** [debauchee/barrier#1628]
### What happened?

For a while, I could move the mouse off the edge of the PopOS screen and the log would in real time show "leaving screen" and which screen it was supposedly entering but the display didn't change.  Likewise, moving the mouse back onto the server's display, the log would show it leaving the client and entering the server but again there was no change to the display.  

The log file is attached.  I changed the log level from warning to debug2 partway through that log.
I also inhibited any but one workspace.  
I am running X11 although some parts of Wayland are installed

[barrier_debug2..txt](https://github.com/debauchee/barrier/files/8393191/barrier_debug2.txt)
.
After stopping and starting the server process, even that doesn't work now.  I do run a Win7 Vbox VM on the server, and have disabled automatic mouse integration although that didn't affect the leaving/entering scenario earlier.  Now, there's no "area" that mouse goes into beyond the server display.

### Version

v2.4.0

### If applicable, where did you install Barrier from?

SERVER:
[Waialua] (PopOS 21.10) - snap installation
snap-id:      5UW67rh7eIO1RsVaAbHx2q5uJGCIvXR6
tracking:     latest/edge
refresh-date: yesterday at 13:01 EDT
channels:
  latest/stable:    2.4.0-4-gac5a1bfd 2021-11-03 (682) 57MB -
  latest/candidate: ↑                                       
  latest/beta:      ↑                                       
  latest/edge:      ↑                                       
installed:          2.4.0-4-gac5a1bfd            (682) 57MB -
  
CLIENTS:

root[Hawi]/root> apt policy barrier
barrier:
  Installed: 2.1.2+dfsg-1
  Candidate: 2.1.2+dfsg-1
  Version table:
 *** 2.1.2+dfsg-1 500
        500 http://us.deb.devuan.org/merged beowulf/main amd64 Packages
        100 /var/lib/dpkg/status

Win7 (AranerIX57) - d/l from github/debauchee/releases  v2.3.0?

MacOS (Lindas-MacBook-Air.local) - also d/l from github/debauchee/releases  v2.4.0

Devuan (Hawi) - root[Hawi]/root> apt policy barrier
barrier:
  Installed: 2.1.2+dfsg-1
  Candidate: 2.1.2+dfsg-1
  Version table:
 *** 2.1.2+dfsg-1 500
        500 http://us.deb.devuan.org/merged beowulf/main amd64 Packages
        100 /var/lib/dpkg/status

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

See install list.

### Relevant log output

```shell
See "what happened" section for attached log file.
```

### Any other information

I'm familiar with Linux and basic troubleshooting.  I was having connection issues until I changed all the configs to not use SSL.  But the non-display of entered clients has been constant:  It's never happened.

**Comment by 54bvc** [comment]
I was under the impression that Barrier was like Chrome Remote Desktop, i.e., a complete KVM replacement.  It appears that is not the case.  The mouse and keyboard part works as apparently intended, so this non-issue can be closed.

**Comment by dimyself** [comment]
why did you close this? i'm having the exact same issue...

I get connected server:client and vice versa

but the only thing that appears to work is the keyboard/mouse/clipboard. The monitor never changes

both my systems are arch linux xfce4

**Comment by p6002** [comment]
Any fix for that?
I have same issue like 4 years ago, and no fix.
Now, on other computers next try for barrier, and what? same issue XD
