### ISSUE TITLE
Drag&Drop on linux?

### ISSUE THREAD

**Issue by PlatinumDragon** [debauchee/barrier#163]
Will there be drag&drop feature support on linux?

**Comment by TheShaman** [comment]
metoo wants, lol.
Even better would be if it worked in mixed Linux/Windoze environments.  

Additional suggestion: mention that it does not work in the readme/docs... spent quite some time trying and searching for solutions before finding out it is simply not supported.

**Comment by AdrianKoshka** [comment]
> Additional suggestion: mention that it does not work in the readme/docs...

I'll try to remember to update the readme with this info.

**Comment by haoyet** [comment]
I have two machines one is on linux and one is on Windows 10 so it would be great if I can drag across those two

**Comment by Sphiinx** [comment]
Yes, please update the readme to reflect that drag & drop doesn't work on Linux. I did the same thing until I found the answer here lol.

**Comment by shymega** [comment]
Linking to #855, issue to remain closed.
