### ISSUE TITLE
Can't download from Azure DevOps

### ISSUE THREAD

**Issue by fridelain** [debauchee/barrier#1695]
### What happened?

I have  tried both Brave Browser and Edge.
https://dev.azure.com/debauchee/Barrier/_build/results?buildId=764&view=artifacts&pathAsName=false&type=publishedArtifacts

I click on "Windows Release installer", or any of the other options, nothing happens.

### Version

v2.4.0

### If applicable, where did you install Barrier from?

I wasn't able to.

### What OSes are you seeing the problem on? (Check all that apply)

Windows

### What OS versions are you using?

Windows 7 SP1 x64

**Comment by JayGuerette** [comment]
There is an almost invisible menu to the far right when you hover. Click on that and select 'Download artifacts'

**Comment by fridelain** [comment]
On the log, I get 'toogle timestamps' only.
After clicking _2 artifacts_ produced, which I already tried before, I get to a list of Published Artifacts. Clicking there on any of them has zero result. I tried a couple different browsers, including Edge.

On the main page linked from GitHub I get 'Download logs', 'view pipeline' and 'view retention leases'

**Comment by fridelain** [comment]
Nevermind, I see it now. Three dots to the right of the artifact in the Published Artifacts list, which you get to by clicking on _2 artifacts_ on the log. Boy was that confusing. Thank you.
