### ISSUE TITLE
no option for fingerprint

### ISSUE THREAD

**Issue by mathse** [debauchee/barrier#171]
### Operating Systems ###

Server: windows 10

Client: Ubuntu 18.04

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

1. ./barrierc -f --enable-crypto hostname.of.server

[2018-11-07T15:20:47] NOTE: started client
[2018-11-07T15:20:47] NOTE: connecting to 'hostname.of.server': 10.10.10.10.:24800
[2018-11-07T15:20:47] INFO: OpenSSL 1.1.0g  2 Nov 2017
[2018-11-07T15:20:47] NOTE: server fingerprint: B8:5F:6D:DC:17:43:59:7C:80:04:DA:14:69:81:5D:02:BA:BD:XX:XX
[2018-11-07T15:20:47] ERROR: failed to verify server certificate fingerprint
[2018-11-07T15:20:54] NOTE: stopped client

### Problem

there is now way (documented) to tell barrier which fingerprint to use

**Comment by AdrianKoshka** [comment]
This should help: https://wiki.archlinux.org/index.php/Synergy#Clients_configuration

**Comment by mathse** [comment]
no, doesn't really help
tried ~/.synergy and ~/.barrier folder

**Comment by AdrianKoshka** [comment]
I think it's `~/.config/barrier`?

**Comment by mathse** [comment]
> I think it's `~/.config/barrier`? I know these instructions work because I've used them before.

could you provide a "tree -d ~/.config/barrier" ?

**Comment by AdrianKoshka** [comment]
Sadly no, I don't have barrier setup anymore.

**Comment by dayne** [comment]
Ubuntu client:
```
.config/barrier
└── SSL
    ├── Barrier.pem
    └── Fingerprints
        ├── Local.txt
        └── TrustedServers.txt
```
The TrustedServers.txt is a single line with the SSL Fingerprint of the Windows Server running barrier.

**Comment by mathse** [comment]
Yep this works

~/.config/barrier
 └── SSL
     ├── Barrier.pem
     └── Fingerprints
         ├── Local.txt
         └── TrustedServers.txt
