### ISSUE TITLE
linux build from source instructions on wiki

### ISSUE THREAD

**Issue by dayne** [debauchee/barrier#173]
I just needed to build on linux again and had to search up my old comment in a closed issue.

Recommend one of the wiki admins add the following as a wiki page at:

https://github.com/debauchee/barrier/wiki/Building-on-Windows

---

## Ubuntu/Debian/Raspbian: Build from source

```
sudo apt update && sudo apt upgrade
sudo apt install git cmake make xorg-dev g++ libcurl4-openssl-dev \
                 libavahi-compat-libdnssd-dev libssl-dev libx11-dev \
                 libqt4-dev qtbase5-dev
git clone git@github.com:debauchee/barrier.git
cd barrier
./clean_build.sh
cd build
sudo make install  # installs to /usr/local/ 
```

**Comment by dayne** [comment]
Note: This is really a re-opening of #28 

I'd be up for helping hack on the wiki if it was opened up to a wider audience to help with documentation.

**Comment by AdrianKoshka** [comment]
Sadly I don't have power to give people access to the wiki. Though you can join `#barrier` in IRC and I'd be willing to help you get write access to the wiki.

**Comment by AdrianKoshka** [comment]
https://github.com/debauchee/barrier/wiki/Building-on-Linux It's rough, and we could expand upon it obviously, but it's there.

**Comment by dayne** [comment]
Thanks!

**Comment by tcpzix** [comment]
i have big problem with 'make install' in fedora 29. 
error : make: *** No rule to make target 'install'.  Stop.

**Comment by hdijkema** [comment]
Building on Debian 9.9 (stretch):

Some small problems with this instruction:

1. The page refers to libqt4-dev. Is this correct? I didn't install the libqt4-dev and it compiled ok.
1.  I had to do one extra install: apt-get install libxtst-dev.

Also some compiler warnings:

```
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
```

Thank you!

**Comment by AdrianKoshka** [comment]
> libqt4-dev. Is this correct?

Probably not

> I had to do one extra install: apt-get install libxtst-dev.

thanks
