### ISSUE TITLE
Barrier GUI requires a display

### ISSUE THREAD

**Issue by Sofiap91** [debauchee/barrier#1735]
### What happened?

Hello,

I've been using barrier for a while now, across several computers with different OS systems. 
Now I've installed barrier on an Ubuntu 14.04 machine, which had its system reinstalled on the same version, but previously had barrier it working. 

Installed it by using snap install, and when I run it on the console I get the following message:

```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
The Barrier GUI requires a display. Quitting...
```

Any ideas are welcome.
Thanks in advance!

### Version

v2.4.0

### If applicable, where did you install Barrier from?

Snap

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Ubuntu 14.04

**Comment by whot** [comment]
The `DISPLAY` environment variable isn't set. Google will have answers for what exactly that means.

Don't know how you get there but the answer is likely somewhere in snap.

**Comment by Sofiap91** [comment]
> The `DISPLAY` environment variable isn't set. Google will have answers for what exactly that means.
> 
> Don't know how you get there but the answer is likely somewhere in snap.

But the DISPLAY variable was set.
I ended up changing to 20.04 for other purposes, so I'll close this.
