### ISSUE TITLE
Support for Ubuntu 22.04.1 LTS (Jammy Jellyfish)?

### ISSUE THREAD

**Issue by mbeltoft** [debauchee/barrier#1794]
### What happened?

Is support for Ubuntu 22.04.1 LTS (Jammy Jellyfish) on the roadmap?
Apparently it uses another display manager now, which does not work with the latest version of barrier.

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Ubuntu 22.04.1 LTS (Jammy Jellyfish)

### Relevant log output

```shell
$ barrier
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

$ export QT_QPA_PLATFORM=wayland
$ barrier
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt-qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix the problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Abort (core dumped)
```

**Comment by Gab-Menezes** [comment]
Bro I was literally delaying the ubuntu update because I'm lazy (was on 20.04), decided to do today and found barrier doesn't work any more =D.

**Comment by Gab-Menezes** [comment]
@mbeltoft try this, worked for me https://github.com/debauchee/barrier/issues/1659#issuecomment-1121964455

**Comment by mbeltoft** [comment]
> @mbeltoft try this, worked for me [#1659 (comment)](https://github.com/debauchee/barrier/issues/1659#issuecomment-1121964455)

Thank you!
It also worked for me.

**Comment by mbeltoft** [comment]
There is a working fix, so I'll allow myself to close this issue.
