### ISSUE TITLE
Client stays on 'Starting' status

### ISSUE THREAD

**Issue by braisgl** [debauchee/barrier#1818]
### What happened?

Just freshly installed Barrier to KVM between Windows (server) and Mac (client) but it never changes to 'Running'
Im using macOS Ventura 13.0, Server IP is the same on both

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

macOS Ventura 13.0
Windows 11

**Comment by igorcafe** [comment]
Same problem here.
I tried to do this https://github.com/debauchee/barrier/issues/1694#issuecomment-1158967053 but it didn't work neither

**Comment by igorcafe** [comment]
For me I am using Ubuntu and Mac, and it doesn't work neither if Ubuntu is the server nor the host.
I have no idea where to find the logs for Mac...

**Comment by braisgl** [comment]
Figured out my problem, but only one solution out of the two possibles: I didn't had an SSL certificate (which you can check by pressing F2 so it will prompt the live log) so I disabled it on both client and server. The thing is that if I wanted to use it, I managed to create it on the Mac client as on that solution, but didn't manage to do it on the Win server
