### ISSUE TITLE
Client not working on x86 platform

### ISSUE THREAD

**Issue by josuah08** [debauchee/barrier#184]
### Operating Systems ###
Server: Windows 10 build 1803 (compilation 17134.407)

Client: Windows 8.1 x86 (32-bit) v6.3 (build 9600)

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

1. Install Barrier 2.1.0 on Windows 10 x64 as a server
2. Install Barrier 2.1.0 on Windows 8 x86 as a client
3. With "Run Barrier now" option immediately an error message appears stating "Process creation error, -216)
4. When "Run Barrier now option" is deselected when program is started manually operating system issues a message "This application will not work on your computer. To find a version for this computer, please contact a software vendor".

### Other info ###
During installation program fetched a correct version of Microsoft  Visual C++ 2017 Redistributable (x86) - 14.10.25017 from the internet.

Messages manually translated from non-english version of OS.

**Comment by AdrianKoshka** [comment]
We don't have a 32-bit x86 build of barrier. Simply because we don't know how much interest there really is for it.

**Comment by AdrianKoshka** [comment]
> My suggestion then is: Either you should provide a build for x86 or make a clear statement in the requirements that only x86_64 platforms are supported..

Probably the latter for now. I'll probably fix up a quick PR or something to make it clear.

**Comment by AdrianKoshka** [comment]
Now the filename on the releases page clearly says `amd64` https://github.com/debauchee/barrier/releases/tag/v2.1.0
