### ISSUE TITLE
macOS 13.1 (22C65) prevents Barrier from running due to permissions issue?

### ISSUE THREAD

**Issue by TheDreamsWind** [debauchee/barrier#1856]
### What happened?

After recent update it seems like macOS doesn't allow Barrier to run. Upon launching the system shows a dialog saying that the app would like to control this computer:

![Screenshot 2022-12-15 at 9 43 36 AM](https://user-images.githubusercontent.com/12813072/207791479-1b9a4ce8-dcb1-47d8-b078-98910b4f02cf.png)

However if you open the privacy & security settings all permissions are already given.

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

macOS Ventura 13.1 (22C65)

**Comment by TheDreamsWind** [comment]
Sorry for rushing with the issue. It seems like the previous permission became obsolete for some reason, so I had to remove the Barrier app from the **Privacy & Security / Accessibility** menu (via the minus button under the list), and after relaunching Barrier again, was able to successfully give the required permission:

![Screenshot 2022-12-15 at 9 50 28 AM](https://user-images.githubusercontent.com/12813072/207792409-a3213d29-6ac8-4441-bb6a-e69f24a6941d.png)

**Comment by ForbiddenEra** [comment]
This worked for me but not first try; even the second try I had to actually click "Open System Settings" in that window even though it was already open and enabled. Was worried that it was pure fkd after MacOS 14 update, I need this software and sucks it's unmaintained and the new fork of this already forked version is not quite ready apparently.. ugh

Weird how this has been forked so many times and there's not (m)any good open source solutions for this and even commercial ones aren't that great.
