### ISSUE TITLE
Mouse left server too early and never showed up on client

### ISSUE THREAD

**Issue by JunOllyLi** [debauchee/barrier#1868]
### What happened?

between two Win 11 machines. Latest Barrier (I think 2.4.0?) as of today. Server is Win 11  Business and client is Win 11 Home.

The moused said to be leaving the server and entered client according to the log, but way too early (around 1/5 of the screen left to the edge), and I cannot see it on the client, and never be able to get it back to the server unless I use the client touchpad to stop the client connection. Originally I thought it may be caused by having two monitors on the server side, but it did not help after I remove the external monitor.

### Version

v2.4.0

### If applicable, where did you install Barrier from?

github official releases page

### What OSes are you seeing the problem on? (Check all that apply)

Windows

### What OS versions are you using?

Windows 11 Business and Windows 11 Home

**Comment by kshashank231** [comment]
Same Here

Barrier Version: 2.4.0
Server: windows 11
Client: MacOs 13

**Comment by timriker** [comment]
I suspect duplicate of #1713

Either run windows at 100% scaling, or revert to 2.3.4

**Comment by JunOllyLi** [comment]
Yes, 2.3.4 works.
Thanks a lot!

**Comment by robertorai** [comment]
Barrier v2.4.0

I use two Windows 11 O.S.
The Server side was 125% scaling.
The Client side is 100% scaling.

Issue: When the mouse pointer pass to the client side, it disappears.
Solution: Set 100% in Server side and now the mouse pointer is correctly shown on Client side.

If set 125% in both machine: doesn't work.
