### ISSUE TITLE
Can't open on Mac

### ISSUE THREAD

**Issue by denvergreene** [debauchee/barrier#1888]
### What happened?

I've been using Barrier for years now, but I just had to do an update on my mac book and afterwards I'm unable to launch Barrier. I'm not totally sure if it's Barrier not working with the new mac patch, or if the patch is specifically antagonistic, as mac tends to be.

When I launch it, I get the screen that says "Accessibility Access", asking me to open system settings to allow Barrier to control the computer. When I go there, I see It already has access so I close the window and try again to the same results.

I've just tried download the newest version to see if that helps and it's just the same thing unfortunately. 

### Version

v2.4.0

### If applicable, where did you install Barrier from?

Sourceforge

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

macOS Ventura 13.1

**Comment by phu-minh** [comment]
Same issues, maybe the Barrier.app does not support the VenturaOS. It was working on MonteryOS.

**Comment by Lingrui98** [comment]
check #1860

**Comment by denvergreene** [comment]
I followed the solution in 1860 and it works for me. I'll close
