### ISSUE TITLE
New / official up-to-date versions of this project?

### ISSUE THREAD

**Issue by ylluminate** [debauchee/barrier#1929]
### What happened?

It seems this project has a lot of pull requests and is not being maintained any longer. Do we have any forks or such projects where someone is currently maintaining this? It appears that @junbujianwpl has some up-to-date builds for Apple Silicon, but it would be nice to see some more/better updates - unless the recommendation might be now to go back to Symless' official project?

### Version

v2.0.0-RC1

### What OSes are you seeing the problem on? (Check all that apply)

Windows, macOS

### What OS versions are you using?

macOS 12 + Windows 10

**Comment by shymega** [comment]
input-leap/input-leap.

**Comment by ylluminate** [comment]
Thanks very much! Have all the PRs effectively been pulled in from here?

**Comment by shymega** [comment]
Kind of. People are welcome to open their PRs on the fork if IL doesn't already have them.

**Comment by ylluminate** [comment]
Curious, I'm not seeing any packages/bins/releases readily available... Am I missing something over there @shymega?

**Comment by shymega** [comment]
@ylluminate We're waiting on a few things before we release v3.0.0. You can use builds from Git for (unsigned) macOS, Windows (GH Actions), or build from Git for Linux. We are more active than Barrier, though, and have a fair amount of bug fixes and refactoring.

**Comment by ylluminate** [comment]
Ah, you mean execute the build script at https://github.com/input-leap/input-leap/blob/master/clean_build.sh to build it. Thanks for pointing that out.

Er, oh, there are also some artifacts under: https://github.com/input-leap/input-leap/actions - but not clear which ones to look at for the builds for macOS. Hmm.

**Comment by shymega** [comment]
Well, we're reworking CI, but I think I'm mistaken - we are building for macOS, but no DMGs. Someone made a Tap for it though.

**Comment by ylluminate** [comment]
Thanks @shymega. I've gone ahead and made an issue to discuss this further: https://github.com/input-leap/input-leap/issues/1638
