### ISSUE TITLE
Pipe character ( | ) not working - British KB, Mac Server Debian Client

### ISSUE THREAD

**Issue by jamess60** [debauchee/barrier#1942]
### What happened?

I am using a macOS server (Ventura 13.4) and a Linux client (Debian 11 + backports) with the latest version of barrier. 
Both systems are set to British PC style keyboard. 

The pipe key works fine on the mac. If I plug an identical keyboard into the client, pipe also works. Pipe does not work over barrier. 

### Version

v2.4.0

### If applicable, where did you install Barrier from?

Here: https://github.com/debauchee/barrier/releases/tag/v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Linux, macOS

### What OS versions are you using?

macOS 13.4 (Ventura) - Server
Debian 11 (Stable + backports) - Client

**Comment by ylluminate** [comment]
AFAIK, the project has moved to: https://github.com/input-leap/input-leap

**Comment by jamess60** [comment]
Indeed it has! Was unaware - thank you
