### ISSUE TITLE
mouse speed is too fast

### ISSUE THREAD

**Issue by tedder** [debauchee/barrier#195]
### Operating Systems ###

Server: Ubuntu 18.10

Client: MacOS 10.14

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

Run server on Ubuntu, client on Mac, when mousing around the client the speed is hyper-fast. This is **not** in games but in normal usage. (it might be in games, but that's how it's different from other tickets)

It's like I'm missing a setting to change the client mouse speed in barrier.

### Other info ###

* When did the problem start to occur? at start
* Is there a way to work around it? No
* Does this bug prevent you from using Barrier entirely? Yes, it's just too twitchy

I can find discussion about this but nothing concrete. It seems like there's gotta be a speed scaling config.

**Comment by osleg** [comment]
That's probably happens when you have different resolutions on your machines.
Eg Linux 4k server and mac 2k client. Mouse will be twice faster on mac because resolution is lower.

**Comment by tedder** [comment]
Thanks. I imagine that's the case. So it isn't configurable? I'm surprised to not see this come up more often as a problem.

**Comment by AdrianKoshka** [comment]
Seems to be a duplicate issue. I can't think back to the original person who had this HiDPI issue, but I've had people report it before.

**Comment by MANTENN** [comment]
I got the same issue but reveresed. Mac mouse is faster and more movement is necessary on Ubuntu.
