### ISSUE TITLE
 Error “Failed to connect to server: timed out” ;

### ISSUE THREAD

**Issue by 0thigs** [debauchee/barrier#1973]
### What happened?

When I try to set up Barrier to share my keyboard and mouse between my Windows 10 server and my Ubuntu 22.04 Linux client, I encounter the error **"Failed to connect to server: timed out."**

This indicates that communication between my client and the Barrier server is not successfully established within a specific time frame.

Additional Information:

-My Windows 10 server is using an Internet connection via USB tethering from my mobile device.
-Both my devices (server and client) are on the same local network.
-My Barrier client is configured to connect to the Barrier server using both the server's name and its IP address.

I have already tried:

-Disabling SSL on both ends
-Attempted to create a separate configuration file 
-Allowed Barrier through the Windows firewall, and even tried disabling the firewall altogether. 

Unfortunately, none of these steps have resolved the issue.

LOGS:

NOTE: started client
NOTE: connecting to '192.168.XX.XXX': '192.168.XX.XXX:24800
WARNING: failed to connect to server: Timed out

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### What OS versions are you using?

Ubuntu 22.04 as Client
Windows 10 as Server

### Relevant log output

```shell
NOTE: started client
NOTE: connecting to '192.168.xx.xxx': '192.168.xx.xxx:24800
WARNING: failed to connect to server: Timed out
```

**Comment by ETLang** [comment]
+1 to this. Barrier was working fine for me all last week. and for some reason today I'm getting this problem. I am not using SSL. My Ubuntu machine and my Windows machine are on the same LAN. I am using default settings for almost everything. I made sure no duplicate processes were lurking in the background. I pinged each machine from the other successfully. I stopped/started both client and server in every sequence possible. Still, I get this same error.

**Comment by 0thigs** [comment]
Bro, I solved my problem. It was because of the USB Tethering.

Probably the problem was IP I was getting from the USB Tethering, but now I am using a LAN cable and it works.

**Comment by 0thigs** [comment]
> +1 to this. Barrier was working fine for me all last week. and for some reason today I'm getting this problem. I am not using SSL. My Ubuntu machine and my Windows machine are on the same LAN. I am using default settings for almost everything. I made sure no duplicate processes were lurking in the background. I pinged each machine from the other successfully. I stopped/started both client and server in every sequence possible. Still, I get this same error.

What are you getting in your LOG?

**Comment by ETLang** [comment]
> 

This morning Barrier decided to work again. I haven't even rebooted.  XD Anyway, next time it misbehaves I'll capture the log at the moment, but to answer your question as best I can, it looked identical to the OP's log.

**Comment by jonathan-analist** [comment]
Aparentemente esse erro acontece somente na rede Wifi
