### ISSUE TITLE
Not working anymore on latest MAC OS

### ISSUE THREAD

**Issue by 4nacs4** [debauchee/barrier#1981]
### What happened?

When opening the app it keeps asking for some permissions to control your computer despite you already allow permissions, also the app doesn't launch anymore

### Version

v2.4.0

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Sonoma 14.0

**Comment by socketbox** [comment]
@4nacs4 I'm considering upgrading to Sonoma and this is of interest to me.

Are you using Sonoma on _both_ the client and the server? If not, and you're able to run Barrier in the machine that's _not_ running Sonoma, please provide logs from that machine.

**Comment by vasac** [comment]
Resetting all decisions with `tccutil` worked in my case:

From shell execute `tccutil reset All barrier` and the next time `barrier` asks you for a permission should be the last one.

**Comment by m-graf** [comment]
See also: https://github.com/debauchee/barrier/issues/1945#issuecomment-1792713158

**Comment by 4nacs4** [comment]
That worked like a charm!!, you rock @vasac

**Comment by 4nacs4** [comment]
Solved!!
