### ISSUE TITLE
Connection Ubuntu 22 - Windows 11 not working

### ISSUE THREAD

**Issue by LucasLevrouw** [debauchee/barrier#2015]
### What happened?

I'm using  a Ubuntu 22 machine as the server, and a Windows 11 machine as the client.

I disabled "Enable SSL" on both machines.

When I connect on the client, I get the messages `NOTE: accepted client connection` and `NOTE: client "client-name" has connected on the server`. And `INFO: connection established`, `server status: active` on the client. When I copy-paste something, I see
INFO: screen "client-name" grabbed clipboard 0 from "server-name"
INFO: screen "client-name" grabbed clipboard 1 from "server-name"
INFO: screen "client-name" updated clipboard 0
INFO: screen "client-name" updated clipboard 1

However, I cannot move my mouse pointer from one display to the other. Also the copy-paste does not work.

When I turn on the DEBUG2 logging, and when moving the mouse pointer to the edge of the screen, I see the following messages on the server
```
DEBUG2: writef(CALV)
DEBUG2: wrote 4 bytes
DEBUG2: msg from "client-name": CALV
DEBUG2: msg from "client-name": CNOP
DEBUG2: no-op from
```

### Version

v2.4.0

### If applicable, where did you install Barrier from?

On Windows: .exe installer
On Ubuntu: via apt

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### What OS versions are you using?

Windows 11 (23H2)
Ubuntu 22.04.4 LTS

**Comment by shouryacoded** [comment]
I had a similar issue, it seems that given how unmaintained the project is, it does not work when using wayland, try again after switching to Xorg in the login screen and it should work as expected.

**Comment by ylluminate** [comment]
Be sure to take this to the living (forked) project: https://github.com/input-leap/input-leap

**Comment by LucasLevrouw** [comment]
> I had a similar issue, it seems that given how unmaintained the project is, it does not work when using wayland, try again after switching to Xorg in the login screen and it should work as expected.

This works, thanks!

**Comment by LucasLevrouw** [comment]
> I had a similar issue, it seems that given how unmaintained the project is, it does not work when using wayland, try again after switching to Xorg in the login screen and it should work as expected.

This works, thanks!
