### ISSUE TITLE
Ubuntu 24.04 as server can't move mouse to right on client

### ISSUE THREAD

**Issue by uzhao** [debauchee/barrier#2036]
### What happened?

I upgrade ubuntu to latest version in recent. My client is a windows machine and it worked well with both windows server and ubuntu 23.10 server with Synergy. After I upgrade ubuntu 23.10 to 24.04, mouse can't move to right on client no matter I place client to left, top or right to the server. Then I tried barrier and got same outcome. When I place client on the top, after I move mouse to client and see this problem, I can still move mouse back to server and mouse moves well on server screen. I don't see any useful information from log as well.

### Version

v2.4.0

### If applicable, where did you install Barrier from?

apt-get

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Ubuntu 24.04

**Comment by uzhao** [comment]
After a few apt-get upgrade it works now

**Comment by kundor** [comment]
> After a few apt-get upgrade it works now

That's all it took? I am having the same issue with a pop-os server while the mouse is on a linux client

Can confirm, an apt upgrade of a bunch of apparently unrelated packages, and a reboot, fixed the issue

**Comment by Deschne** [comment]
I can't even start synergy on 24.04....:(
