### ISSUE TITLE
OSX Client: Modifier Keys don't work in remote control applications

### ISSUE THREAD

**Issue by githubjsorg** [debauchee/barrier#204]
### Operating Systems ###

Server: Windows Server 2008

Client: macOS 10.12.6 Sierra

### Barrier Version ###

2.1.0

### Steps to reproduce bug ###

1. Connect to a remote machine with one of these (MS Remote Desktop, NoMachine)
2. Try to use SHIFT, CTRL, ALT, SUPER.
3. These keys are not recognized as being depressed on the remote machine.

### Other info ###

* When did the problem start to occur? When I switched to Barrier. I used to use Synergy 1.3.
* Is there a way to work around it? No
* Does this bug prevent you from using Barrier entirely? No

Interestingly CTRL, ALT, and SHIFT work just fine in VNC but not SUPER.

I only switched to Barrier after updating from Maverics to Sierra because Synergy wouldn't recognize modifier keys at all on the client. Using Synergy in Maverics, modifier keys worked just fine even in remote control apps.

**Comment by AdrianKoshka** [comment]
Hey, thanks for submitting an issue. I'll get back to this probably after December 26th. Visiting relatives for the holidays right now.

**Comment by githubjsorg** [comment]
You're welcome. Have fun with your relatives. :)

When you get back, let me know if I can help with any additional information or testing fixes.

**Comment by githubjsorg** [comment]
Adrian, thank you for the update. How do I get a new binary(s) to test with? And do I need a new one for both win and macos or just 1 or the other?

**Comment by AdrianKoshka** [comment]
You would have to build barrier yourself from source for both platforms from master, I have no ETA on when 2.2 will be released.

**Comment by githubjsorg** [comment]
I see a guide on how to build on Windows, which I might be able to do.
https://github.com/debauchee/barrier/wiki/Building-on-Windows
Any chance this will work with VS 2017?

But I don't see a guid on how to build on macos.

**Comment by AdrianKoshka** [comment]
> Any chance this will work with VS 2017?

Don't know, I just use Visual Studio Community because the instructions say to

> But I don't see a guide on how to build on macos.

No one has written one, sorry.

**Comment by p12tic** [comment]
@githubjsorg See what we do in .travis.yml.

Basically, on OSX you need to install ports and do the following:

```
sudo port -N install qt5-qtbase openssl
sh -x ./clean_build.sh
```

**Comment by AdrianKoshka** [comment]
@p12tic Do you have access to the wiki? If so, writing up a "how to compile" page for macOS would be helpful if you know how.

**Comment by p12tic** [comment]
I don't have access unfortunately.

**Comment by AdrianKoshka** [comment]
Darn, I mean, you could write up something on gist.github.com and then when you're happy with it, link me to it so I can fold it into the wiki, if you want that is.
