### ISSUE TITLE
Can't download and install barrier on kali linux

### ISSUE THREAD

**Issue by NJ-Khan** [debauchee/barrier#2108]
### What happened?

I am not able to install barrier on Kali Linux. from this repository.
it prompts  the following error.
1: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err8)

### Version

v2.0.0-RC1

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

kali linux

### Relevant log output

```shell
.
```

### Any other information

.

**Comment by Ayx03** [comment]
<https://github.com/debauchee/barrier/releases/tag/v2.4.0>

```
WARNING
Barrier is no longer maintained and no longer receives improvements and security fixes. The primary developers have moved to the [InputLeap project](https://github.com/input-leap/input-leap). The newest release of InputLeap is [3.0.2](https://github.com/input-leap/input-leap/releases/tag/v3.0.2)
```

**Comment by salimshre** [comment]
Instal it from snap store

Snap Store app | Kali Linux
☑ Commands:

$ sudo apt update
$ sudo apt install -y snapd
$ sudo systemctl enable --now snapd apparmor
$ sudo snap install snap-store
$ sudo nano /home/username/.zshrc
       export PATH=$PATH:/snap/bin
$ source /home/username/.zshrc
$ init 6

**Comment by nbolton** [comment]
Please try Deskflow or Input Leap as Barrier is no longer in development.

https://github.com/deskflow/deskflow
https://github.com/input-leap/input-leap

Both are compatible with Barrier client/server so you can try on one of your computers.

If this is still an issue in those projects, we would appreciate a cross-post of this issue.

Not sure which to use? The 'Insights' tab of each project may help you decide.
