### ISSUE TITLE
Unable to build linux version - git clone failing

### ISSUE THREAD

**Issue by RichardLebel** [debauchee/barrier#220]
I am following the instructions to build the linux version (on Linux Mint version 19.1 - Ubuntu derivative)  as indicated on https://github.com/debauchee/barrier/wiki/Building-on-Linux but when I get to the git clone command, I get the following:

$ git clone git@github.com:debauchee/barrier.git
Cloning into 'barrier'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Araevin** [comment]
Try `git clone https://github.com/debauchee/barrier.git` instead of 
`git clone git@github.com:debauchee/barrier.git`

**Comment by RichardLebel** [comment]
I eventually downloaded the source and rebuilt it locally.
