### ISSUE TITLE
Drag and drop file transfer not working

### ISSUE THREAD

**Issue by petko10** [debauchee/barrier#226]
### Operating Systems ###
Manjaro Linux (Arch based, AUR package), KDE on the server machine
Windows 10 on the client machine.

### Barrier Version ###
Version 2.2.0 on the server
Version 2.1.0 on the client (no 2.2 build available for windows)

### Steps to reproduce bug ###
Try to drag and drop the file and the mouse stops on the screen edge (from either computer)

**Comment by AdrianKoshka** [comment]
Drag and drop isn't support on linux.

**Comment by Askmewho** [comment]
It will be supported in the future???

**Comment by AdrianKoshka** [comment]
Only if someone puts in the effort.

**Comment by Askmewho** [comment]
I am sorry, thats an stallman answer btw hahahha. Lovely work here. It rocks on my pi's synchronized with my x86 pcs.

**Comment by AdrianKoshka** [comment]
It's an honest one…if nobody puts forth the effort to get drag & drop working for Linux, it won't happen. 🤷

**Comment by shymega** [comment]
Closing in favour of #855.
