### ISSUE TITLE
Last flatpack version not establish connection

### ISSUE THREAD

**Issue by cccaballero** [debauchee/barrier#244]
### Operating Systems ###

Server: Ubuntu 18.04

Client: Ubuntu 18.04

### Barrier Version ###

2.2.0 (flatpack)

### Steps to reproduce bug ###

1. Install last flatpack version in client and server
2. Try to connect

### Other info ###

* Was working without issues with previous not-flatpack versions
* I can't look to logs because #243

**Comment by cccaballero** [comment]
Compiling it from scratch works without issues

**Comment by TheShaman** [comment]
Weird. Using latest flatpak as server on Solus Linux with autoconfig Windoze client, zero issues (even reconnects  whenever I need to stop the server/restart it).

**Comment by cccaballero** [comment]
I will test it more deeply tomorrow and will post the logs. Flatpack packaged app tray icon is also not working in Ubuntu 18.04.

**Comment by AdrianKoshka** [comment]
> app tray icon is also not working in Ubuntu 18.04.

Yeah, that's related to GNOME 3. I think we dealt with the issue in PR #237, that change hasn't made it into a release yet.
