### ISSUE TITLE
Version info in v2.1.2 is wrong

### ISSUE THREAD

**Issue by kakra** [debauchee/barrier#248]
These lines in v2.1.2 tag are wrong:
https://github.com/debauchee/barrier/blob/53ebc47ace7486d0b7ba975e58506c4a9f28acd6/cmake/Version.cmake#L4

Probably a merge glitch that slipped through...

Building this version results in the binary identifying itself as 2.2.0 while it isn't. I think this problem has also been there already in a previous version.

**Comment by AdrianKoshka** [comment]
Yeah, forgot to update some metadata.

**Comment by yjqg6666** [comment]
so is the release version which should be 2.1.2 instead of 2.2.0.

**Comment by parkerlreed** [comment]
Yeah 2.20 still links to https://github.com/debauchee/barrier/archive/v2.1.2.tar.gz

**Comment by AdrianKoshka** [comment]
Yeah…it's not high priority and I'm on vacation right now…

**Comment by mirh** [comment]
This is fixed.. I guess?

**Comment by shymega** [comment]
As of commit 8e8b38b493d031f5007bebc44e8f767482e41fb6, it has been updated to 2.3.0. I can see from commit 73c13ab023399f6d181644f3b1360eba07914571, the version take is 2.2.0.

@walker0643 How can we fix this? I'd rather _not_ rewrite the Git history, but I'm sure we can release another tag... let me know, and I'll make a fix.

**Comment by mirh** [comment]
... I don't know which commits you are picking up, but it seems just right here
https://github.com/debauchee/barrier/blob/v2.3.1/cmake/Version.cmake

**Comment by shymega** [comment]
Didn't look look like it from my end.

**Comment by shymega** [comment]
Ah.. I've just seen my repo is a few commits behind 😅 I guess we can close this issue now.
