### ISSUE TITLE
Update linux build instruction on wiki for Fedora

### ISSUE THREAD

**Issue by Nanoseb** [debauchee/barrier#254]
Hi,
Sorry this is not an issue but more a pull request for the wiki.
I have just compiled and installed barrier on Fedora and hence I had to adapt the package list needed  from the one on the wiki. Here is the list I used:

```
sudo dnf install git cmake  gcc-c++ xorg-x11-server-devel \
                 libcurl-devel avahi-compat-libdns_sd-devel \
                 libXtst-devel qt5 qt5-devel openssl-devel
```
Maybe someone can update the wiki and add this?

Thank you all for this fork,

Seb

**Comment by AdrianKoshka** [comment]
Yep, no problem!
