### ISSUE TITLE
Disconnecting due to unrecognised client name

### ISSUE THREAD

**Issue by Polokniko** [debauchee/barrier#259]
### Operating Systems ###

Server: Windows Version 1803 (OS Build 17134.590)

Client: Arch Linux version 4.20.7

### Barrier Version ###
2.1.0

### Steps to reproduce bug ###

1. Install barrier on Windows and Arch Linux
2. Start server on Windows and client on Arch Linux
3. Create screen names on either device
4. Try and connect to server.

### Other info ###

Server simply doesn't allow client because it's screen name was unrecognized. No apparent method to add to a list of trusted screen names. I've set both screen names to arbitrary values.

**Comment by Polokniko** [comment]
for others with this same issue, you have to click and drag the monitor in the top right down into the middle space in "Server Configuration". Assumed it was just an indicator at first, didn't realize it was a widget.

**Comment by lky100047** [comment]
> > for others with this same issue, you have to click and drag the monitor in the top right down into the middle space in "Server Configuration". Assumed it was just an indicator at first, didn't realize it was a widget.
> 
> can u elaborate!! i see that pc icon was in center! now what we have to do ?

drag the pc icon near the Server PC, than double click the name "Unnamed" to edit the name to client's PC name. You can find the client's name on the Client's PC barrier, at the 'Screen name:' part.
