### ISSUE TITLE
Pointer disappearing - HiDPI related?

### ISSUE THREAD

**Issue by Mibo5354** [debauchee/barrier#273]
### Operating Systems ###

Server: Windows 10 1809 - 1920x1080 with 125% scaling

Client: Manjaro Linux - 1366x786

### Barrier Version ###

2.1.0-RELEASE-0b2dfd80

### Steps to reproduce bug ###

1. Turn on Barrier and connect the machines
2. On server 
3. Move mouse around and try to move to the other machine
4. Pointer disappears and does not reappear
5. Disconnect from the client machine to restore pointer

### Other info ###

* When did the problem start to occur? Since I set it up
* Is there a way to work around it? No, I tried tweaking the hidpi setting for barriers.exe but nothing worked. HiDPI settings has changed from 1709 hence workaround listed in #42 is not applicable. On a side note, is there binaries for 2.2 mentioned in the other issue so I can see if it is fixed?
* Does this bug prevent you from using Barrier entirely? Yes

There seem to be a window of movement on the server machine that is equal to the resolution of the client. The window starts from the top left corner and I can move the pointer without it disappearing but when it moves out it disappears until I disconnect.
This occurs on synergy [1.4.12] as well, that's why I tried out barrier.

**Comment by pgetsos** [comment]
Have the same issue, workaround didn't work as well

**Comment by tungmeister** [comment]
I've got the same issue, my mouse will disappear after moving ~75% over my main monitor and it's practically impossible to get it to appear again.

**Comment by noisyshape** [comment]
I suspect this is the same issue as #206, #194, and #94. The problem is resolved for me with a 2.2.0 build.

**Comment by Mibo5354** [comment]
@noisyshape is there binaries for a 2.2.0 build?

**Comment by noisyshape** [comment]
@Mibo5354 No there aren't. It looks like there are some problems with the Windows build system. The binaries compile fine though and I can email you a zip file if you're desperate enough.

**Comment by Mibo5354** [comment]
@noisyshape is the instructions on the wiki still good, or is there any changes I should know about?

**Comment by noisyshape** [comment]
@Mibo5354 The instructions are good. Just follow them carefully. Once you have the binaries, stop all Barrier processes and copy everything into your existing installation folder. If you can't complete the build, start a new issue and I'll try to help.

**Comment by sommoMicc** [comment]
> @Mibo5354 No there aren't. It looks like there are some problems with the Windows build system. The binaries compile fine though and I can email you a zip file if you're desperate enough.

Plz can you upload somewhere (like in google drive) the 2.2.0 Windows build?

**Comment by Mibo5354** [comment]
@sommoMicc Here's the build that I compiled today https://drive.google.com/file/d/1S3Z5mLQT63ZTWIsjiTyzL9qdIjoE-MW1/view?usp=sharing

**Comment by AdrianKoshka** [comment]
> > @Mibo5354 No there aren't. It looks like there are some problems with the Windows build system. The binaries compile fine though and I can email you a zip file if you're desperate enough.
> 
> Plz can you upload somewhere (like in google drive) the 2.2.0 Windows build?

This should be happening soon-ish™? Waiting for a PR to fix something with the windows installer script. Then I'll be able to make a build and official release.

**Comment by Mibo5354** [comment]
The issue is solved with the newer build, should I close this issue?

**Comment by sommoMicc** [comment]
> The issue is solved with the newer build, should I close this issue?

Yes. Now it works

**Comment by gerroon** [comment]
Hi,

I just bought a 4k monitor and I am hitting this issue. I use 2.4.0 on all 3 Pcs. The servers is a Win10 x64 4K monitor. The cursor disappears around the edges of the 4K monitor, it looks like the cursor is somewhere on one of the clients  but hard to tell, no logical or visual control is possible.

**Comment by gregors613** [comment]
I've just installed 2.4.0.1 on a Windows 10 machine with 2 monitors( 1K and 4K ) and on Linux with the mirrored ( 4K and 1K ). The win10 machine is configured as the server and the linux machine as the client. Monitors are arranged left to right Win10 1K Win10 4K Linux 4K Linux 1K. When I start the server and move my mouse around on the windows machine, it will suddenly disappear and if I press the menu key, the menu on the linux machine appears ( no mouse cursor ) and the following appears in the log 

[2022-01-10T11:20:40] DEBUG2: clamp to right of "gregors-linux-pc"
[2022-01-10T11:20:40] DEBUG2: clamp to bottom of "gregors-linux-pc"

**Comment by gerroon** [comment]
@gregors613 going back to 2.3.4 fixes my issue.

**Comment by qmdnls** [comment]
Same issue here on 2.4.0 to provide another data point. Ubuntu server with Windows 10 client on a 4K monitor (with 150% fractional scaling). Monitors are arranged side by side and when moving the mouse over to the Windows client the cursor does not appear for a few seconds.

Going back to 2.3.4 solved the issue for me too.

**Comment by spacewalk01** [comment]
@gerroon same downgrade on windows works, finally ( - ⌓ - )
