### ISSUE TITLE
Check to see if VS2019 works for building on windows.

### ISSUE THREAD

**Issue by AdrianKoshka** [debauchee/barrier#277]

**Comment by noisyshape** [comment]
clean_build.bat has a hard coded cmake generator string for VS2017 and there is no Qt library specifically for VS2019 yet. Changing ``"Visual Studio 15 2017 Win64"`` to ``"Visual Studio 16 2019"`` allows for a successful build. I'm running the binaries as both client and server and they seem to be fine.

**Comment by AdrianKoshka** [comment]
It does? I remember changing that and not getting a sucessful build.

**Comment by noisyshape** [comment]
I get 3 warnings, but I think they're the same warnings I get with VS2017. The only other change I made was setting the Qt version to 5.12.2. Try building again off of master and post the errors if you get any.

**Comment by AdrianKoshka** [comment]
Ah, I was building off tag `v2.1.2`.

**Comment by AdrianKoshka** [comment]
A PR to update `clean_build.bat` to compile against vs2019 would be appreciated, if you want to that is.

**Comment by noisyshape** [comment]
Done. It looks like the Appveyor is getting a bad argument, however.

**Comment by AdrianKoshka** [comment]
Appveyor has been broken for PRs.
