### ISSUE TITLE
We'ved moved to flathub

### ISSUE THREAD

**Issue by AdrianKoshka** [debauchee/barrier#279]
This is more of a PSA than an issue, but the flatpak has been moved to flathub. You can find instructions on what to do if you currently have the previous barrier flatpak installed, here:

https://github.com/debauchee/barrier/releases/tag/v2.1.2

**Comment by jasonsyoung** [comment]
Just an FYI, their is a typo in the release notes for this version. "flatpack" is used twice, when it should be "flatpak"

**Comment by AdrianDC** [comment]
The issue remains for the 2.2.0 release :

> 3. And finally: `flatpack install flathub com.github.debauchee.barrier`

**Comment by AdrianKoshka** [comment]
Ugh, thanks
