### ISSUE TITLE
Release number inconsistency 2.1.2 vs 2.2.0

### ISSUE THREAD

**Issue by kgyrtkirk** [debauchee/barrier#296]
I think during releasing the 2.1.2 a small typo was made:
On the github releases page; the release 2.2.0 has a tag of 2.1.2

see:
https://github.com/debauchee/barrier/releases

**Comment by AdrianKoshka** [comment]
In my opinion, it's not a huge problem, and I don't see the point of fixing it.

**Comment by brianjmurrell** [comment]
So what will the next release be then?

It is rather confusing, IMHO.

**Comment by AdrianKoshka** [comment]
I don't know at the moment, but the tag and version in the application will match.
