### ISSUE TITLE
Use XDG spec directories

### ISSUE THREAD

**Issue by AdrianKoshka** [debauchee/barrier#31]
Using the `XDG` specification directories would not only make the linux package work better as a flatpak, but play nicer with distributions in general. This was mentioned in #30.

- `XDG_CONFIG_HOME`
- `XDG_DATA_HOME`
- `XDG_CACHE_HOME`

flatpak specific [docs](http://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories)
[XDG Base Directory spec as documented by FreeeDesktop](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by walker0643** [comment]
@AdrianKoshka if i missed anything with the patch let me know. thanks for the suggestion!

**Comment by AdrianKoshka** [comment]
Looks good, haven't tested. Did you make a new release? Flathub doesn't allow just pointing to master if the source is a git repo.

**Comment by walker0643** [comment]
Nope. Tagging will happen once I hear from the various package maintainers that they do not need any additional code changes in order to proceed.

**Comment by AdrianKoshka** [comment]
Alright, I'll keep an eye out then for whenever the next tag is out.

**Comment by walker0643** [comment]
2.1 tagged
