### ISSUE TITLE
IPv6 Connections refused to Linux server

### ISSUE THREAD

**Issue by ramesh45345** [debauchee/barrier#32]
Referencing issue #18, when connecting to an Ubuntu 18.04 server running barriers (git master 0b5ca57b), a Fedora 27 client (same barrier version) connecting via IPv6 (resolved from the avahi hostname resolution as well as router hostname resolution) receives a connection refused message. Both the server and client are using SSL, and both work fine when an IPv4 address is hard-coded. The following log is generated on the client (Fedora 27):

```
[2018-04-27T08:48:15] NOTE: connecting to 'rkrishna-pc': 2601:cb:8100:9400::f2f:24800
	/var/tmp/barrier/src/lib/client/Client.cpp,146
[2018-04-27T08:48:15] INFO: OpenSSL 1.1.0h-fips  27 Mar 2018
	/var/tmp/barrier/src/lib/net/SecureSocket.cpp,839
[2018-04-27T08:48:15] WARNING: failed to connect to server: Connection refused
	/var/tmp/barrier/src/lib/barrier/ClientApp.cpp,301
[2018-04-27T08:48:16] NOTE: connecting to 'rkrishna-pc': fd5b:88e:f3e5::f2f:24800
	/var/tmp/barrier/src/lib/client/Client.cpp,146
[2018-04-27T08:48:16] INFO: OpenSSL 1.1.0h-fips  27 Mar 2018
	/var/tmp/barrier/src/lib/net/SecureSocket.cpp,839
[2018-04-27T08:48:16] WARNING: failed to connect to server: Connection refused
	/var/tmp/barrier/src/lib/barrier/ClientApp.cpp,301
[2018-04-27T08:48:17] INFO: stopping barrier desktop process
[2018-04-27T08:48:17] NOTE: connecting to 'rkrishna-pc': 2601:cb:8100:9400::f2f:24800
	/var/tmp/barrier/src/lib/client/Client.cpp,146
[2018-04-27T08:48:17] INFO: OpenSSL 1.1.0h-fips  27 Mar 2018
	/var/tmp/barrier/src/lib/net/SecureSocket.cpp,839
```

The following log is generated on the server running Ubuntu 18.04 (basically nothing, since the server doesn't hear anything from the client):
```
[2018-04-27T08:46:54] INFO: starting server
[2018-04-27T08:46:54] INFO: config file: /tmp/Barrier.h26056
[2018-04-27T08:46:54] INFO: log level: INFO
[2018-04-27T08:46:54] NOTE: started server, waiting for clients
	/var/tmp/barrier/src/lib/barrier/ServerApp.cpp,540
```
Note: The openssl version on the server is as follows:
```
[2018-04-27T08:48:17] INFO: OpenSSL 1.1.0g  2 Nov 2017
	/var/tmp/barrier/src/lib/net/SecureSocket.cpp,839
```

### Operating Systems ###
Server: Ubuntu 18.04
Client: Fedora 27
Both updated to latest software from repositories.

### Barrier Version ###
git master 0b5ca57b, compiled on their respective machines. After upgrading to Ubuntu 18.04, barrier was recompiled as a precaution.

### Steps to reproduce bug ###

1. On the client, either specify an IPv6 address for the server (this I didn't test), or use a hostname which resolves to an IPv6 address first through avahi or router name resolution (this was used in my case).
2. Ensure SSL is enabled on both the client and server.
3. Ask the client to connect. The client will not be able to connect, saying connection refused.
4. Replace the IPv6 address with an IPv4 address.
5. Connection will work properly.

### Other info ###
Bug doesn't prevent me from using barrier, however it is inconvenient since hostname resolution is IPv6 first on all my networks, and then IPv4. As a workaround, I'm not sure if barrier can ask for an IPv6 address first from avahi, and then an IPv4 address?

**Comment by walker0643** [comment]
HI @ramesh45345  -

This is a very well-written bug report. Thank you! We're currently short on IPv6 developers but I've asked a couple people to have a look at this. Hopefully we can get you up and running shortly. Stay tuned!

**Comment by AdrianKoshka** [comment]
If it helps any, I know IPv6 works on barrier, I have my server bound to `::1`. (client remote port-forwards connection over SSH and connects)

**Comment by ramesh45345** [comment]
Thanks a bunch @walker0643 . I think this should be easily reproducible, I have another set of machines using barrier (Ubuntu 18.04 on the client, and Fedora 27 on the server, the reverse of my bug report above), and seem to have the same problem. Connection refused when I use the avahi IPv6 autoconfigured address. @AdrianKoshka , what git revision of barrier are you using (or released version, if applicable)? Perhaps I should test an older version and see if I have the same problem.

**Comment by AdrianKoshka** [comment]
Release `2.0.0`

**Comment by wltjr** [comment]
Just to chime in here, I did not author, but I did update the IPv6 patches for Synergy. Which I believe is the basis for this in Barrier. Looking back over that [patch](https://patch-diff.githubusercontent.com/raw/symless/synergy-core/pull/6178.patch) in symless/synergy-core/pull/6178. Even in the original symless/synergy-core/pull/4499. It was just patching lib, client and server, not gui. Based on that, it seems there may have been further IPv6 changes done as part of the work in Barrier.

@walker0643 that may be a partial answer to your question 2. Seems they furthered the code into the GUI and something maybe off there. Which is why one works and the other does not.

I can see about taking a look there, but not sure if I can help at all. I was contacted regarding the patches and this issue. Thus chiming in, and I am happy to help if I can.

**Comment by walker0643** [comment]
It's entirely possible that the GUI is to blame. The GUI does not open any sockets nor do any real networking itself, it simply starts barriers/barrierc (and barrierd on windows) and passes configuration params as arguments.

@ramesh45345 Can you enable debugging info in the GUI settings window (any level INFO and above iirc) and compare the arguments that it passes to barriers/barrierc to those that you were using above?

**Comment by wltjr** [comment]
I would assume something is being passed incorrectly from UI to CLI, however that is done. It seemed above a port was duplicated. I do not use any UI with synergy, just text config and starting via cli. That part should be good to go with any IPv6 address.

**Comment by ramesh45345** [comment]
@walker0643 Here is the output from the server:
```
[2018-05-10T07:46:33] INFO: starting server
[2018-05-10T07:46:33] INFO: command: /usr/local/bin/barriers -f --no-tray --debug DEBUG2 --name rkrishna-pc --enable-crypto -c /tmp/Barrier.i22916 --address :24800
[2018-05-10T07:46:33] INFO: config file: /tmp/Barrier.T22916
```
I think in modern version of barriers the ":24000" is unnecessary? In my command line post earlier, I fed an IPv6 address into barriers, however ideally I would have wanted to accept connections from alll IPv6 and IPv4 addresses.

**Comment by walker0643** [comment]
That's very helpful. Can you test the dualstacked branch to see if it fixes this?

https://github.com/debauchee/barrier/tree/dualstacked

**Comment by ramesh45345** [comment]
Hmm, using the dualstacked branch (4806a66a), I am still getting the same result.

Server command:
```
[2018-05-11T17:22:06] INFO: starting server
[2018-05-11T17:22:06] INFO: command: /usr/local/bin/barriers -f --no-tray --debug DEBUG2 --name HomeLaptop --enable-crypto -c /tmp/Barrier.Woawqk --address :24800
[2018-05-11T17:22:06] INFO: config file: /tmp/Barrier.WcMPIT
[2018-05-11T17:22:06] INFO: log level: DEBUG2
```

Client log (same version, 4806a66a):
```
[2018-05-11T17:23:50] NOTE: connecting to 'HomeLaptop': fd7f:7549:7489::2cc:24800
	/mnt/nasvol/DLs/barrier/src/lib/client/Client.cpp,146
[2018-05-11T17:23:50] INFO: OpenSSL 1.1.0h-fips  27 Mar 2018
	/mnt/nasvol/DLs/barrier/src/lib/net/SecureSocket.cpp,839
[2018-05-11T17:23:50] WARNING: failed to connect to server: Connection refused
	/mnt/nasvol/DLs/barrier/src/lib/barrier/ClientApp.cpp,301
```

Looks like the GUI is still not listening on IPv6 by default. IPv4 still works normally. The above client log was taken with avahi resolution of the IPv6 address. It seems that if you fill in the IPv6 address into the client GUI manually, it still duplicates the port:
```
[2018-05-11T17:28:09] WARNING: failed to connect to server: unknown error for: fd7f:7549:7489::2cc:24800:24800
	/mnt/nasvol/DLs/barrier/src/lib/barrier/ClientApp.cpp,301
```

**Comment by walker0643** [comment]
Take 2 ... this time barriers will tell you explicitly which socket family it's using. There will be a NOTE-level line in the debug output stating either
- NOTE: started server (IPv4), waiting for clients
or
- NOTE: started server (IPv4/IPv6), waiting for clients

Also you can confirm via netstat or another similar tool (netstat -46l for example) whether or not barrier has opened the correct socket type.

**Comment by ramesh45345** [comment]
Excellent! It works! It did start in IPv6/IPv4 mode, and the client was able to connect using the avahi name resolution.

Server:
```
[2018-05-12T10:25:27] INFO: starting server
[2018-05-12T10:25:27] INFO: config file: /tmp/Barrier.EwSlum
[2018-05-12T10:25:27] INFO: log level: INFO
[2018-05-12T10:25:27] NOTE: started server (IPv4/IPv6), waiting for clients
```

There is only one small issue remaining, and that is manually inputting an IPv6 address into the client GUI's "Server IP" field. It still yields the following results in 5bc3fef8:
```
[2018-05-12T10:31:52] INFO: starting client
[2018-05-12T10:31:52] INFO: command: /usr/local/bin/barrierc -f --no-tray --debug DEBUG2 --name HomeServer --enable-crypto fd7f:7549:7489::2cc:24800
[2018-05-12T10:31:52] INFO: config file: /tmp/Barrier.lvqIHI
[2018-05-12T10:31:52] INFO: log level: DEBUG2
[2018-05-12T10:31:53] NOTE: started client
	/mnt/nasvol/DLs/barrier/src/lib/barrier/ClientApp.cpp,393
[2018-05-12T10:31:53] WARNING: failed to connect to server: unknown error for: fd7f:7549:7489::2cc:24800:24800
```
I admit that I probably won't rely on this much, but I can see this bug needing to be fixed at some point. I believe the way it is working right now, for an IPv6 address, I can't specify the port using the command line in order for it to connect properly. For example, using the following command (without the GUI) on the client works:
```
barrierc -f --enable-crypto fd7f:7549:7489::2cc
```
However, this results in the port error seen above:
```
barrierc -f --enable-crypto fd7f:7549:7489::2cc:24800
```
I suspect the issue is specifc to parsing the semi-colons in IPv6 addresses (a wild guess on my part). Might explain why hostnames or IPv4 addresses work just fine with ports.

**Comment by yupi2** [comment]
Wrapping the IPv6 address in brackets seems to be the notation used to separate port and address (since IPv6 uses colons). https://serverfault.com/questions/205793/how-can-one-distinguish-the-host-and-the-port-in-an-ipv6-url

Would need to change parsing in https://github.com/debauchee/barrier/blob/24987e069496b185ad88de09657dced2a73189ef/src/lib/net/NetworkAddress.cpp#L60
and then make the GUI put brackets around IPv6 addresses I imagine.

**Comment by ramesh45345** [comment]
No further complaints from me, 92e8e1e seems to be working regarding everything reported above. Thanks a bunch for your work on this, its a really appreciated fork of the synergy codebase.
