### ISSUE TITLE
Switch previous or next source [change typing language] - 

### ISSUE THREAD

**Issue by soylisK** [debauchee/barrier#329]
### Operating Systems ###

Server: Ubuntu 18.04

Client: Ubuntu 16.04

### Barrier Version ###

2.2.0

When I am in client side control, shortcut for changing typing language [input source] doesn't work. I use Shift + ALT.

**Comment by mhidro** [comment]
Alt+Shift is also the default input language switch key combination in Windows.  But it can also be configured to be ctrl+shift or "Grave Accent".

**Comment by soylisK** [comment]
I know that I ALt+Shift is default for windows, I had created by my self to work with this combination of keys on my laptop since ever and it was fine. Anyway at the end I changed shortcut combination keys to something like super+shift , and it worked with barrier too!
