### ISSUE TITLE
Windows XP support?

### ISSUE THREAD

**Issue by MrGlasspoole** [debauchee/barrier#335]
Server: Windows 10 Pro (x64)
Client: Windows XP Media Center 2005 SP3 (x86)
Barrier Version: 2.2.0

Should Barrier work on Windows XP?
I can't find any information about the OS Versions that are supported.

In Windows XP (x86) when starting Barrier i get the message:
C:\Program Files\Barrier\barrier.exe is not a valid Win32 application

**Comment by AdrianKoshka** [comment]
Windows XP is EoL as far as I'm concerned. We don't even support 32-bit windows platforms.

**Comment by AdrianKoshka** [comment]
I did update the README to reflect this though, thanks.

**Comment by noisyshape** [comment]
To the best of my knowledge, there's no technical reason you couldn't compile a 32-bit version and install it on XP. There's little interest in either of these things though and certainly nobody around to support them. You might try an older version of Synergy or maybe Mouse Without Borders.

**Comment by parkerlreed** [comment]
Would an older synergy for the XP and barrier on Linux work together? Or do the versions have to match?

**Comment by parkerlreed** [comment]
To answer my own question: no. Protocol error.

**Comment by mirh** [comment]
Protocol error is more about synergy-barrier incompatibilities than "releases version". 
#227 
If you patched the handshake maybe it could work, see also these builds https://github.com/debauchee/barrier/issues/92#issuecomment-403238829

**Comment by Kharzette** [comment]
I just tried building a version for winXP (I'm doing some old original xbox stuff and need XP), and had success with just the command line bits (no QT stuff).  There weren't that many code changes; most of the work was getting the build environment set up.

Anyone interested will need visual studio community 2017 (which is tricky to get to).  When setup is run, you'll want the v140 build tools.  CMake-gui had some trouble with that but I eventually got it going by using the command line cmake from the 2015 x86 command prompt.  There's a cmake option to build without GUI and that helps tremendously as you don't need QT.

Once the project files are generated, edit each one and replace v140 with v140_xp.

I defined a preprocessor variable WINVER at 0x0501 (winxp) to make it easy to ifdef around the unsupported stuff.  There might be a way to have cmake do that but I'm not good with cmake.

After that there's just a few shell/winsock changes I'll stick in a fork.  I don't really think it is pull request worthy.  There's not a really good way to set the OS you are building for.

**Comment by mirh** [comment]
Why not *v141* and *v141_xp*?

**Comment by Kharzette** [comment]
Hmm I didn't see a 141 in visual studio setup.

**Comment by fennectech** [comment]
would you be willing to provide a binary version for XP?   im familiar with the command line  but compiling windows software is not something i can do

**Comment by Kharzette** [comment]
Well, just a build off my machine would probably be a bad idea, but maybe the github actions stuff can build it?  I'll check into that.

**Comment by Kharzette** [comment]
I've got an xp build working over on my fork.  There's no installer or QT stuff but I think most would just need barrierc for an old xp machine.
