### ISSUE TITLE
Use hostname instead of ip?

### ISSUE THREAD

**Issue by fredlllll** [debauchee/barrier#337]
would it be possible to use a servers hostname instead of the ip? my very crappy routers dhcp constantly gives a new ip to my server, but the hostname stays the same. many other applications can use hostnames in place of the ip, would this be possible here too?

**Comment by AdrianKoshka** [comment]
I don't see any reason it wouldn't be possible.

**Comment by chrisokuda** [comment]
It works fine, I use it that way with the `.local` TLD (my barrier server is at `name.local`, for example).

**Comment by fredlllll** [comment]
@chrisokuda thanks for the tip! i tried it without .local and it doesnt work that way. maybe it should be mentioned somewhere that this needs .local

**Comment by chrisokuda** [comment]
You have to set that .local up yourself somehow, I used my router, but that's beyond the scope of this thread.

**Comment by fredlllll** [comment]
@chrisokuda interesting, i didnt have to set anything up. usually just using my computers hostname works for lan network stuff, but for barrier i added .local to the name and suddenly it worked. i have a german telekom router. speedport something something. maybe they have it builtin
