### ISSUE TITLE
Arch Linux AUR package available

### ISSUE THREAD

**Issue by Tblue** [debauchee/barrier#34]
I created an Arch Linux AUR package: https://aur.archlinux.org/packages/barrier/

Just in case you want to link it in the wiki... :-)

**Comment by walker0643** [comment]
Hi @Tblue - do you plan to maintain this package in the AUR? if so we'll list it for the next release and credit you as the maintainer.

**Comment by Tblue** [comment]
Yes, I plan to maintain the AUR package for now.

Thanks!

**Comment by walker0643** [comment]
2.1 tagged

**Comment by Tblue** [comment]
AUR package updated.

**Comment by walker0643** [comment]
https://github.com/debauchee/barrier/wiki

You're officially the AUR maintainer :smile:
