### ISSUE TITLE
UFW firewall enabled--barrier stopped working 

### ISSUE THREAD

**Issue by Snerken** [debauchee/barrier#348]
### Operating Systems ###

I'm using Ubuntu 18.10 and ferenOS (bionic beaver)

### Barrier Version ###

2.2.0

### Steps to reproduce bug ###

I activated the UFW firewall and allowed port 22 for ssh. Barrier now fails to communicate across my four laptops. When UFW is disabled, Barrier is back in business. How do I keep firewall and Barrier operating at the same time?

Cheers

Snerken

**Comment by AdrianKoshka** [comment]
Did you open the port barrier/synergy use? (Port 24800)

**Comment by Snerken** [comment]
`root@tosh-ubuntu:/home/snerx# ufw allow 24800`

```
root@tosh-ubuntu:/home/snerx# ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere                  
24800                      ALLOW       Anywhere                  
22 (v6)                    ALLOW       Anywhere (v6)             
24800 (v6)                 ALLOW       Anywhere (v6)             

root@tosh-ubuntu:/home/snerx# 

```

That did the trick. 

_Merci bien_
