### ISSUE TITLE
Barrier running problem (again): Windows (server) and Linux Mint (client) 

### ISSUE THREAD

**Issue by Gorbz** [debauchee/barrier#351]
### Operating Systems ###

Server: Windows 10 with GPU nVidia GTX 1050i
Client: Linux Mint 19.1 w/ Cinnamon version 4.0.9 and Linux Kernel 4.15.0-20-generic and GPU nVidia GTX1080i  (driver version 390.116)

### Barrier Version ###

2.3.0 (latest by July 2, 2019)

### Steps to reproduce bug ###

Barrier installed in both machines. In the server (Windows) I allow barrier.exe and barrierc.exe to pass through Microsoft Defender (and Firewall). I disabled SSL in both machines. 

Server runs normally: "Barrier is runnin"
Client gives : "Barrier is starting".

Screen names match!
Server IP's match!
Machines computed in the same network!

### Other info ###

* When did the problem start to occur? When I installed it. Immediately.
* Is there a way to work around it? No.
* Does this bug prevent you from using Barrier entirely? Yes

I would really like to ask for some help.

**Comment by AdrianKoshka** [comment]
Just tested with a server of windows 10 and a client of Fedora 30 (flatpak), and things worked just fine.

**Comment by Gorbz** [comment]
I am not sure how this is helping. I am sure it works for many people. I am seeking for some tips or hints on possible things I might have skipped or performed wrong.

**Comment by AdrianKoshka** [comment]
Did you configure the server in the configuration panel?

![image](https://user-images.githubusercontent.com/8690255/60744557-93562680-9f44-11e9-9d6c-537ac9c10124.png)

**Comment by AdrianKoshka** [comment]
![image](https://user-images.githubusercontent.com/8690255/60744574-a7018d00-9f44-11e9-9421-9fa233b3a562.png)

**Comment by Gorbz** [comment]
UPDATE: 

I used another machine with Linux mint (laptop this time) at my home WIFI network and it worked perfectly fine. 

Previously I have been trying to make it work via my institutions network connected by ethernet cables in both devices. Could this possibly affect Barrier?

**Comment by AdrianKoshka** [comment]
Possibly?

**Comment by Gorbz** [comment]
So I have tried again via the network. The two computers see each other in a secure network. The barrier on the client is still not starting.

@AdrianKoshka I am new into Linux and Github and I have limited experience on what affects what etc. I would appreciate if you could help me use this amazing piece of software. I apologize for naive questions.

**Comment by dregimbal** [comment]
@Gorbz have you tried installing from source on the linux machine?

**Comment by Gorbz** [comment]
@dregimbal No. I was just using the app manager of Linux Mint. Will it make a difference? I am trying it now.

**Comment by AdrianKoshka** [comment]
I don't think building from source would fix the issue, but it looks like you either need to add a public ssh key to your github account, or clone over https. Though you could just download a release archive from the releases section. https://github.com/debauchee/barrier/releases

**Comment by Gorbz** [comment]
FINAL UPDATE:

It works now. I build from source as suggested above. One thing is that instead of 

`git clone git@github.com:debauchee/barrier.git`

I used

`git clone https://github.com/debauchee/barrier `

It would be nice if:

1. You could help new users of github etc with more analytic instructions (ok, I know its not hard, but some people will have their first Build experience here)
2. Inform people it is better to built from source rather than download the app from Linux app manager

This software is awesome. Thanks.

**Comment by AdrianKoshka** [comment]
> Inform people it is better to built from source rather than download the app from Linux app manager

I personally strongly disagree with this, package managers exist for a reason. Nobody should _have_ to build from source every time they want to use an application.

**Comment by Gorbz** [comment]
@AdrianKoshka You are right. But for some reason the Barrier would not work properly using Mint's "Software Manager".

**Comment by AdrianKoshka** [comment]
🤷 I don't know why this would be, I don't use mint, and haven't spun up a VM of mint to test this yet.

**Comment by p12tic** [comment]
@Gorbz : I would file a bug to Mint distribution. Maybe their packaging scripts do something wrong.

**Comment by AdrianKoshka** [comment]
fwiw, I think mint uses the flatpak, I could be wrong.

**Comment by dregimbal** [comment]
I suggested building from source instead of using the flatpak because it didn't work for me on the flatpak on Ubuntu either
Glad you got it working @Gorbz

**Comment by m3chstaa** [comment]
I have the same problem using Pop_OS!
Barrier just gets stuck at "Barrier is starting".
I tried the command above "git clone https...." but still didn't work. When I run barrier now I can see in the terminal window it has a problem...
"The program 'barrier' called 'DNSServiceRegister() which is not supported in the Apple Bonjour compatibility layer of Avahi.

**Comment by shymega** [comment]
On this date - Tue, Jun 02, 2020 at 02:55:50PM -0700, m3chstaa wrote:
> I have the same problem using Pop_OS!
> Barrier just gets stuck at "Barrier is starting".
> I tried the command above "git clone https...." but still didn't
> work. When I run barrier now I can see in the terminal window it has
> a problem...

I'm confused what you mean by this. Are you saying you built Barrier
from Git..?

> "The program 'barrier' called 'DNSServiceRegister() which is not
> supported in the Apple Bonjour compatibility layer of Avahi.

OK, what version is your copy of Avahi?

--
Kind regards,
Dom Rodriguez (shymega)

**Comment by m3chstaa** [comment]
I'm sorry for my lack of knowledge. Tell me what you need to know and I'll try and find out. How do I find my version of Avahi?
I have not built barrier from git as I don't know how to do that.

Kind regards,

Lee.

________________________________

**Comment by m3chstaa** [comment]
Hi

Okay I found that "avahi-daemon" is the newest version (according to OS), (0.7-4ubuntu7)

Thanks,
Lee

________________________________

**Comment by m3chstaa** [comment]
Hi

I've also just found, when I run "barrier" from terminal it says, "Failed to load module "appmenu-gtk-module"

Lee.

________________________________

**Comment by m3chstaa** [comment]
Operating Systems
Server: Windows 10 
Client: Pop_OS!. Tried also with latest (20.04) Ubuntu Linux

Barrier Version
2.3.2 (Build date 10th Nov 2019)

Steps to reproduce bug
Barrier installed in both machines. In the server (Windows) I disabled all security such as defender and real-time protection.

Server runs normally: "Barrier is running"
Client gives : "Barrier is starting".

Screen names match
Server IP's match

Other info
When did the problem start to occur? When I installed it. Immediately.
Is there a way to work around it? No.
Does this bug prevent you from using Barrier entirely? Yes
I would really like to ask for some help.

**Comment by shymega** [comment]
Whoops, didn't mean to open that.

**Comment by m3chstaa** [comment]
> FINAL UPDATE:
> 
> It works now. I build from source as suggested above. One thing is that instead of
> 
> `git clone git@github.com:debauchee/barrier.git`
> 
> I used
> 
> `git clone https://github.com/debauchee/barrier `
> 
> Gorbz I don't suppose you could help me by telling me how you "build from source" as you described there?

**Comment by shymega** [comment]
@m3chstaa [Here](@m3chstaa https://github.com/debauchee/barrier/wiki/Building-on-Linux) for Linux, and [here](https://github.com/debauchee/barrier/wiki/Building-on-Windows) for Windows...

**Comment by maldex** [comment]
Disable SSL on the windows server side helped for me

**Comment by xsudiptaster** [comment]
[2021-06-15T10:34:05] ERROR: process exited with error code: 9

2021-06-15 10:34:07.180 barrierc[47557:432352] starting cocoa loop

This is where my Mac log stops when use Windows 10 as the server

**Comment by AvgOrdinaryGuy** [comment]
Hey guys!  I've been using Barrier for a few months now, and everything was dandy.  But then two or three weeks ago, I switch client laptops (stopped using Windows 10 and swapped in a Debian 10 laptop), and after trying to change configurations, have not been able to get Barrier working again since on the Kubuntu server.  "Barrier is Starting" is as far as it ever goes.  The client machines still start fine.  So far I've tried making sure the firewall is disable, installed from repositories, snap and built from source from git.  Same result all different ways.
