### ISSUE TITLE
Mouse cursor invisible in Linux/Gnome 3.30.2 on Wayland client

### ISSUE THREAD

**Issue by LIII-XXII** [debauchee/barrier#358]
### Operating Systems ###

Server: Windows 10 1809 17763.557

Client: Gentoo / Gnome 3.30.2 on Wayland

### Barrier Version ###

2.1.2 from pixlra overlay: qt5, openSSL

### Steps to reproduce bug ###

The mouse cursor does not appear on the Linux/Wayland client.
I can click things, type text, etc, but the mouse cursor is not visible...

### Other info ###

I saw that there is a possible workaround by enabling mouse cursor even with touch screens in Gnome, but the setting does not seem to be there in my Gnome version.

```
gsettings set org.gnome.settings-daemon.plugins.cursor active false
No such schema “org.gnome.settings-daemon.plugins.cursor”
```

**Comment by AdrianKoshka** [comment]
There is no wayland support unfortunately.

**Comment by LIII-XXII** [comment]
I have XWayland libraries though, which claim to be downwards compatible with X server interfaces. I believe the mouse cursor not being visible is actually caused by some gnome usb tablet settings disabling the cursor icon, because everything works besides that.

**Comment by LIII-XXII** [comment]
```
xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:17                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:17            	id=7	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:17                    	id=8	[slave  keyboard (3)]
```

**Comment by frohro** [comment]
I just installed Ubuntu 21.04, and it uses Wayland by default.  I noticed this behavior too.  You can click on things, and it works.  It is just you cannot see the position of the mouse cursor.  For example, some programs change the display when the mouse hovers over something.  You can click on that and it work fine.  When I saw "no Wayland support," I didn't expect it to look so very close to working.  I can even type things just fine.  It is just difficult to figure out what will receive the text.

**Comment by pangyuteng** [comment]
for those that updated to Ubuntu 21.04, you could just opt for Xorg during login - during the password prompt, click `Ubuntu on Xorg` at the bottom right corner. cheers.

**Comment by nicecil** [comment]
jjjj
