### ISSUE TITLE
How it is going debian packaging

### ISSUE THREAD

**Issue by rodrigocam** [debauchee/barrier#38]
I want to contribute with this project (I think it is a really good tool!!), so I read #22 issue, and I don't know how it is going the progress to make a .deb package. I have build a .deb for my own, and if there is anything I can help, I will be at your disposal (:

**Comment by walker0643** [comment]
Hi @rodrigocam - Thanks for offering to help! As I understand it our debian packager is in the process of getting the package added to the repositories. It's been a rather slow process, I admit, but we should be seeing packages appear "soon"(TM) :stuck_out_tongue:

**Comment by rodrigocam** [comment]
Oh cool! I hope the best for you guys :smiley:
