### ISSUE TITLE
Keyboard not being shared since macOS update (10.14.6 (18G87))

### ISSUE THREAD

**Issue by domparry** [debauchee/barrier#393]
### Operating Systems ###

Server: macOS Mojave 10.14.6 (18G87)

Client: macOS High Sierra 10.13.6

### Barrier Version ###

2.1.0 and 2.3.0 

### Steps to reproduce bug ###

1. Open Barrier on both machines
2. Move the mouse into the screen of the client.
3. Mouse control is transferred and works normally.
4. Keyboard still active on server, but not on client

### Other info ###

* When did the problem start to occur? Since running the latest macOS update (on 7-08-2019)
* Is there a way to work around it? No
* Does this bug prevent you from using Barrier entirely? No

**Comment by domparry** [comment]
Just as an update, I've tested this on 2.3.1 and it still persists.

**Comment by domparry** [comment]
Something I see in the logs when I switch to the other machine:
```2019-08-30 17:28:53.195 barriers[1353:12766] pid(1353)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
```

**Comment by AdrianKoshka** [comment]
That's a long-time warning, iirc it's doesn't interfere with anything.

**Comment by metadave** [comment]
I'm experiencing the same issue. I added a bunch of traces throughout the source to log events (EventQueue, OSXKeyState, OSXScreen etc), and it appears that only mouse events are being fired. If anyone has pointers on where I should be looking in the source, I'd be happy to debug some more.

**Comment by domparry** [comment]
Any work around on your side to get it going again @metadave ?

**Comment by jbirthisel** [comment]
This is happening to me off and on all the time.

**Comment by metadave** [comment]
> Any work around on your side to get it going again @metadave ?

not yet, still debugging and learning about iokit. All signs currently point to keyboard events not being fired on the server.

**Comment by noisyshape** [comment]
I couldn't reproduce this with VMware guests and I'm not seeing any difference in behavior with 10.14.6. This may be identical to https://github.com/symless/synergy-core/issues/6513 where supposedly it's something to do with input source settings.

When all else fails, post full debug logs.

**Comment by domparry** [comment]
I've double checked the keyboard input source settings as described in that issue, and that's not the case here. @noisyshape When you say full debug logs, are you referring to something more than the logs shown from the `show log` function? If there's a way to turn on more detailed logs, let me know and I'll happily do so.

**Comment by noisyshape** [comment]
@domparry In the settings dialog (F4) there is a logging level option. Set it to Debug2 and restart the client/server. If you can log a short session with a couple of failed keystrokes that could be helpful. You can use pastebin for this.

**Comment by domparry** [comment]
Here you go @noisyshape . It just seems like the keyboard events are never sent. There isn't an error in the logs. I've included both the client and server logs below.

Client Log: https://pastebin.com/KUxd7XVb
Server Log: https://pastebin.com/fgnUDvpf

However, after creating these, I saw a new SSL error appear in the logs that might be unrelated (Posting below in case it's relevant):

```
[2019-09-09T08:02:40] NOTE: client "Dominics-MacBook-Pro.local" is dead
[2019-09-09T08:02:40] ERROR: ssl error occurred (generic failure)
[2019-09-09T08:02:40] ERROR: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
[2019-09-09T08:02:41] INFO: OpenSSL 1.0.2s  28 May 2019
[2019-09-09T08:02:41] INFO: accepted secure socket
[2019-09-09T08:02:41] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2019-09-09T08:02:41] NOTE: accepted client connection
[2019-09-09T08:02:41] NOTE: client "Dominics-MacBook-Pro.local" has connected
[2019-09-09T08:02:55] INFO: switch from "Dominics-MacBook-Pro-161.local" to "Dominics-MacBook-Pro.local" at 0,532
[2019-09-09T08:02:55] INFO: leaving screen
[2019-09-09T08:02:55] INFO: screen "Dominics-MacBook-Pro-161.local" updated clipboard 0
[2019-09-09T08:02:55] INFO: screen "Dominics-MacBook-Pro-161.local" updated clipboard 1
2019-09-09 08:02:55.111 barriers[71818:514983] pid(71818)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
[2019-09-09T08:02:58] INFO: switch from "Dominics-MacBook-Pro.local" to "Dominics-MacBook-Pro-161.local" at 1858,316
[2019-09-09T08:02:58] INFO: entering screen
```

**Comment by domparry** [comment]
Please let me know if there is anything else I can provide to help find the cause of this. It essentially makes barrier unusable.

**Comment by domparry** [comment]
@metadave, you're awesome. Spot on. My issue was secureinput locked by a startup app (workflowy).

**Comment by domparry** [comment]
I'm closing this because it's solved (And not a Barrier issue)

**Comment by iulo** [comment]
@metadave thanks bro, save my life.
for other who face on this problem, a possiable solution is just: locking and unlocking your system.

**Comment by royriojas** [comment]
> @metadave thanks bro, save my life.
> for other who face on this problem, a possiable solution is just: locking and unlocking your system.

This is the simplest solution so far... many many thanks @iulo

**Comment by shabeer** [comment]
thanks @iulo for the quick solution
