### ISSUE TITLE
Uninstall ubuntu

### ISSUE THREAD

**Issue by jaroslawjanas** [debauchee/barrier#394]
I installed barrier from source on ubuntu. How do I uninstall it? 
Can't find any help anywhere.

**Comment by AdrianKoshka** [comment]
Have you tried running `make uninstall` from the `build` directory?

**Comment by ScriptingDad** [comment]
I actually just tried `sudo make uninstall` and got `make: *** No rule to make target 'uninstall'. Stop`
As for the second question, the reason I came to when I installed barrier from snap and it would connect but the cursor never moved over was, does master branch fix this?

**Comment by AdrianKoshka** [comment]
What snap did you install? I'm currently going through the process of reclaiming the name `barrier` on the snap store.

**Comment by shymega** [comment]
@jaroslawjanas Did you install to `/usr/local`?

**Comment by jaroslawjanas** [comment]
I did everything you guys mentioned. 
But the thing that worked from me was:
- install it again from the ubuntu software application rather than compiling it yourself
- and then uninstall it from there

It removed pretty much everything.

**Comment by shymega** [comment]
Great to hear. Closing now.
