### ISSUE TITLE
Moving From Windows to Ubuntu doesn't work

### ISSUE THREAD

**Issue by rainybreeze777** [debauchee/barrier#42]
### Operating Systems ###

Server: Windows 10 version 1709 (OS build 16299.431)

Client: Ubuntu 18.04 LTS

### Barrier Version ###

2.1.0-Release

### Steps to reproduce bug ###
1. Establish server on Windows
2. Establish client on ubuntu
3. Set up server monitor configuration such that ubuntu is on the left of windows
4. Log reports connection is successful
5. Attempts to move cursor from windows to the left of the screen to ubuntu machine
6. Cursor disappears on Windows, cursor does not appear on Ubuntu
7. Ubuntu can accept keyboard strokes and mouse clicks, but cursor does not move
8. Cannot move cursor back to Windows, had to manually stop Ubuntu client for the cursor to return to windows

### Other info ###

* When did the problem start to occur? 
When I just finished setting up Barrier and establish connection, first attempt at using
* Is there a way to work around it? No
* Does this bug prevent you from using Barrier entirely? Yes

**Comment by AurisAudentis** [comment]
I can attest to the same issue on Linux Mint Sylvia 18.3.

**Comment by dayne** [comment]
Sounds like these issues from synergy-core: 

* https://github.com/symless/synergy-core/issues/4041
* https://github.com/symless/synergy-core/issues/6070

**Comment by walker0643** [comment]
Can you try 075d4f4 and report back? If you're not comfortable building from source you could wait for the next release, 2.2. Thanks!

**Comment by walker0643** [comment]
Please reopen if you still have this issue after upgrading to 2.2. Thanks!

**Comment by xurongchen** [comment]
> I can attest to the same issue on Linux Mint Sylvia 18.3.
> Is there any workaround/fix availiable or in the works?
> 
> UPDATE:
> found a workaround: properties of the executable barrier -> compatibility -> all users -> High dpi options -> check all the boxes.
> After this, the program seems to work as intended. This was a known problem in synergy.

Thanks! However I solved the problem by setting the executable 'barrriers' but not the 'barrier'.

**Comment by ScriptingDad** [comment]
@AurisAudentis your workaround still worked in 2.3.1.  Thanks!  not sure why it worked but I've been playing with this for 4 hours now and this is the only thing that did the trick.

**Comment by stevesobol** [comment]
I'm having the same problem with macOS, as detailed in a bug that was marked as a dupe of this one. It existed in Synergy 1.8 and the workaround there was to turn off clipboard sharing, which I have done, but I'd rather have it enabled.

**Comment by rstacruz** [comment]
> executable barrier -> compatibility -> all users -> High dpi options -> check all the boxes.

I'm on barrier 2.4.0 in Windows 11, and what worked for me was this, but on the executable `barriers.exe` (not `barrier.exe`).

**Comment by MyAlfisti** [comment]
Server: Windows 11
Client: macOS
Problem: This combination does not work when Server is 2.4.0

Do you have a plan to fix this problem?

**Comment by liamjwang** [comment]
@MyAlfisti Uninstalling v2.4.0 and installing v2.3.4 on Windows 11 (barrier server) fixed the problem for me.
I'm using the barrier client v2.4.0 on Ubuntu 18.04.

**Comment by DarwinDemian** [comment]
Found a fix, this was happening because of the screen scaling. I was using 100% with Linux, and 125% on Windows. After setting the scaling to 100% on Windows, the mouse started working on the other screen.

**Comment by sexycode** [comment]
> Found a fix, this was happening because of the screen scaling. I was using 100% with Linux, and 125% on Windows. After setting the scaling to 100% on Windows, the mouse started working on the other screen.

thanks change to 100% on windows , mouse is OK

**Comment by ultrageek** [comment]
I'm not seeing any setting to change screen scaling. Where is this, please?

Server: Windows 10 (V2.4.0)
Client: MacOS (Ventura 13.0)

**Comment by xyz1001** [comment]
Another resolution is change the barrier exe compability setting. Right click exe, select properties, Compability and click "Change high DPI settings" button, check "override high DPI scaling behavior" and select Application. Barrier will works ok after restart.
![image](https://user-images.githubusercontent.com/14332136/228723392-532b9629-3366-44a8-8a7e-32bc301b75af.png)

**Comment by PhantomKing99999** [comment]
Hi, I've gone through all debugging options listed in this thread including Compatability options, Changing scaling, and disabling Clipboard sharing. The program is still not working.

**Comment by SteveClement** [comment]
The DPI settings tweak still works ;)

**Comment by Migelo** [comment]
November update, still works!

**Comment by aaomidi** [comment]
Is there a solution for Linux server and MacOS client users?
