### ISSUE TITLE
Right Alt doesn't work

### ISSUE THREAD

**Issue by wjtk4444** [debauchee/barrier#438]
### Operating Systems ###

Server: Any (Linux?)
Client: Any (Windows?)

### Barrier Version ###

Any

### Steps to reproduce  bug ###

1. Open on-screen keyboard on Windows client - it highlights currently pressed modifier keys
2. Press LSHIFT, LCTRL, LALT, RALT, RCTRL, RSHIFT
3. Noitice that only RALT doesn't light up when pressed

### Other info ###

I only use one language other than English, but I think that solving this issue could also close many others related to keyboard layouts and typing in non-latin characters.

> Polish is written with the standardized Polish alphabet, which has nine additions to the letters of the basic Latin script (ą, ć, ę, ł, ń, ó, ś, ź, ż).

For instance, to type `ą`, I have to press `RALT+a`. It does work on the host, but it doesn't on the client. When I toggle the right alt manually (via on-screen keyboard), it works as expected.

I would suspect that Windows uses another keycode for RALT than Linux, and it simply ignores whatever is being sent.
`key ef7e is not on keyboard` 
is what I get from DEBUG1 on client.

**Comment by wjtk4444** [comment]
So, after (two?) years of using Barrier (and other syngery forks) almost everyday, I finally realized there's an option to configure it with a [.conf file](https://github.com/symless/synergy-core/wiki/Text-Config). Apparently, it allows one to remap keys at will. Well, better late than never.

Looking at some [issue threads](https://github.com/symless/synergy-core/issues/4411) while also trying things out and failing (a lot), those are the two lines that fixed the issue. It looks like it makes no sense (if anything, I expected `altgr = alt` to work instead of this), but it just works.

```
section: screens
    linux:
    windows7:
        meta = altgr
        altgr = shift
end
```

So, it seems that 
* the issue can be worked around
* I'm an idiot for not reading the ~~f@!#ing manual~~ readme file earlier

Not sure if there's a point in keeping this one open - not a Barrier specific bug and it's already reported and described well enough in [synergy-core](https://github.com/symless/synergy-core). I'm leaving the decision on whether to close or keep this one open to repository maintainers.

**Comment by p12tic** [comment]
@AdrianKoshka Does it make sense to close the issue?

**Comment by AdrianKoshka** [comment]
I suppose so, if this issue needs to be re-opened, it can be.

**Comment by Elexy** [comment]
This saved me from insanity.

For reference: I use a wired mac keyboard on a Linux server and mixed Windows10 / linux clients

**Comment by wrzomar** [comment]
For me it doesn't work. Only the `altgr = alt` makes altgr "work" - the underscored characters appear in the window menu (like with left alt), but with alt the shortcuts work, with altgr not. Both client and server are using Linux. What am I missing?

**Comment by metebyte** [comment]
Server (installed through release DMG):
  macOS Monterey 12.3.1
  Barrier Version: 2.4.0-release-3e0d758b

Client (installed through Pacman): 
  Arch Linux 5.17.1
  Barrier Version: 2.4.0-release
  Protocol version 1.6

Keyboard Layout on Server:
  Turkish Q
  
Keyboard Layout on Client:
  trq

Tried every method related to this issue. But couldn't get any good result.

**Comment by Eugeniusz-Gienek** [comment]
Works for Mac - I have a couple of linuxes + mac and when writing Polish letters you use alt + a letter. Right alt didn't work so this is a revelation! Thanks!!!
