### ISSUE TITLE
libqt5corea Dependancy is not satisfiable.

### ISSUE THREAD

**Issue by ssc412018** [debauchee/barrier#440]
Hi,

Trying to install Barrier on Linux Mint. But I get the error "Depndancy is not Satisfiable : libqt5core5a >= 5.12.2. Checked my system and qt module was already installed. 

What I a doing wrong here? I am trying to install using the deb file.

**Comment by p12tic** [comment]
Indeed, this is packaging problem, the bug needs to be raised with whoever produced the package for Linux Mint. We unfortunately can't fix this problem. I'm closing the report.
