### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by ScrPits** [debauchee/barrier#451]
apparently malware.
avast didnt like this program.

anyways on to something better.

**Comment by EbonJaeger** [comment]
Barrier is not malware, it's just a case of a garbage antivirus program giving a false positive, likely because of a new release that it simply hasn't seen yet.

**Comment by shymega** [comment]
Just because Avast says its malware - it does _not_ necessarily mean it _is_. As per @EbonJaeger said, yes, its because of a false positive. I recommend that you report the offending warning as a false positive to Avast themselves.

Closing this issue and marking as invalid.
