### ISSUE TITLE
Caps Lock issue

### ISSUE THREAD

**Issue by RichardPhilipsRoy** [debauchee/barrier#452]
Caps lock on/off isn't working properly on the barrier client

**Comment by shymega** [comment]
Could you provide more information? You've barely told us what OS you're using for the client and server, the version of Barrier on both the client and server, any kind of context when the bug occurs, etc.

We have an issue template for a reason, and its meant to be filled out when you file a bug.

I will close this issue if we don't hear back with more information in 48 hours. Thanks.

**Comment by shymega** [comment]
Its now been 24 hours. Closing this issue and marking as invalid.

You are welcome to reopen this issue and provide further information, however.
