### ISSUE TITLE
Question: Linux change Keyboard layout on client  

### ISSUE THREAD

**Issue by remotejob** [debauchee/barrier#462]
Server: Ubuntu 18.04.3
Client: Ubuntu 18.04.3

Keyboard: FI on both

But when I use Barrier on client side keyboard changed on US layout
Question: how change Keyboard on client side in my case it will be FI?

**Comment by shymega** [comment]
What version of Barrier are you using? Or from Git?

**Comment by remotejob** [comment]
from Git

**Comment by shymega** [comment]
Try using the latest release, or, if that doesn't work, try using previous releases (maybe three?), to see if its a regression. Generally there's no real need to build from Git... any reason why you're doing that?

**Comment by remotejob** [comment]
#437 help in may case setxkbmap fi

No particularly reason a part I am programming about 3 decades and use only Linux so compiling
more natural for me.

**Comment by shymega** [comment]
I get that.. I use Gentoo, so I prefer compiling as well, but have you tried building from the last Git tag then, rather than master - unless you're already doing that...?

Let me know how you get on with #437..

**Comment by remotejob** [comment]
Gentoo was my favorite distribution for many years.
I resolved  my issues by commands from client terminal:

 #437  setxkbmap fi

#436  xset  dpms force on
xset s 600

**Comment by shymega** [comment]
Alright. I'll close this issue for now, glad you sorted it.
