### ISSUE TITLE
Is the all communication (mouse, keyboard, copy file) encrypted?

### ISSUE THREAD

**Issue by vasili111** [debauchee/barrier#463]
I am interested if all communication (mouse, keyboard, copy file) is encrypted? Is there any unencrypted communication?

**Comment by AdrianKoshka** [comment]
If you have SSL enabled, then to my knowledge, the data sent over the network is encrypted.

**Comment by vasili111** [comment]
@AdrianKoshka Where is the SSL setting located in order to enable it? I could not find that setting.

**Comment by AdrianKoshka** [comment]
`Barrier` -> `Settings`.
