### ISSUE TITLE
Barrier Stuck At "Barrier Is Starting"

### ISSUE THREAD

**Issue by RyomanMC** [debauchee/barrier#480]
So i installed it on both my windows 7 and ubuntu machines. i set up a server on the win pc but when i try to connect on my linux pc it gets stuck at "Barrier Is starting". i have ubuntu 18.04.3 LTS

Here Is the log:
Qt: Session management error: None of the authentication protocols specified are supported
("-f", "--no-tray", "--debug", "INFO", "--name", "Ryan-Ubuntu", "--enable-crypto", "[192.168.0.135]:24800")
("-f", "--no-tray", "--debug", "INFO", "--name", "Ryan-Ubuntu", "--enable-crypto", "[192.168.0.135]:24800")
("-f", "--no-tray", "--debug", "INFO", "--name", "Ryan-Ubuntu", "--enable-crypto", "[192.168.0.135]:24800")
("-f", "--no-tray", "--debug", "INFO", "--name", "Ryan-Ubuntu", "--enable-crypto", "[192.168.0.152]:24800")

**Comment by kylergibson** [comment]
I had similar issue, but I did not look at the log to see what it said. 

How I resolved it, is on the server machine select configure server and delete all machines that are in "Screens and links". Once I did that and reloaded barrier on both machines it was working. Hope this helps.

**Comment by minhmoc** [comment]
I just recently have the same issue. 
I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
Hope this help.

**Comment by BrickmanRodrigo** [comment]
> 
> 
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

Having the same issue and this one worked for me, thanks

**Comment by RyomanMC** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

I Tried This And It Worked! Thanks

**Comment by rahul4u2019** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

Awesome man, it worked for me too. I was stuck from last hour or so. Thanks a ton.... :)

**Comment by edegaudenzi** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

Worked here as well, cheers!

**Comment by wgmao** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

Amazing ! (Win10 as server, Ubuntu16 as client)

**Comment by zeerd** [comment]
I got the same problem. and after I drag the icon the added a new computer, it would work, too.
But, when I closed the SSL, it works.

**Comment by verajosemanuel** [comment]
same here, added a screen on server config with the name of the client computer, reloaded, but client is stuck on "Barrier is starting"

**Comment by livejamie** [comment]
> I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too.
> But, when I closed the SSL, it works.

Disabling SSL fixed it for me as well.

**Comment by Aerglonus** [comment]
> [SOLVED ]same here, added a screen on server config with the name of the client computer, reloaded, but client is stuck on "Barrier is starting".
> Server is connected to network via RJ45 cable, but Client via WIFI. Both to same router
> SOLVED DISABLING FIREWALL

[SOLVED] [ EXTRA SOLUTION]
I had the same setup and disabling windows firewall worked but to keep windows firewall running i added an Inbound rule to the 24800 port (the one that barrier is using) in Windows defender firewall with advanced security after barrier started to work again with firewall enabled again.

**Comment by jsantosdias** [comment]
Hello! Tried everything: Disabling SSL, Disabling Firewall and nothing... What can I do?

**Comment by toty88** [comment]
I cant seem to make it work from Windows 10 (server) to arch (client). I Tried doing what @minhmoc says, I tried disabling firewall completely and ssl but still no results.
I know there's got something to do with Windows cause I tried from two arch machines and it worked flawlessly!

**Comment by chingham** [comment]
Tried everything too and still have this problem with macOS (Server) and Windows 10 (Client)

**Comment by ryukinix** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.


In my opinion that should be on FAQ.

**Comment by surajkamblesk** [comment]
> I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too.
> But, when I closed the SSL, it works.

yes this one and one solution by @minhmoc worked for me.

**Comment by ccsben** [comment]
In my case, because I've tried multiple times starting and closing Barrier on the Windows machine as the server, the application doesn't actually exist. So make sure there is not an existing barrier process running in task manager. Then start barrier again which should be able to run.

**Comment by iFreilicht** [comment]
When you're installing barrier as a snap, don't install it via a UI! Install it via the terminal like so:

`snap install --devmode barrier`

This will circumvent all security sandboxing snap normally applies to an install, which prevents barrier from accessing the network socket properly. I'm sure there's a way to fix this when building the snap package, but as a workaround, this was good enough for me.

**Comment by maxiberta** [comment]
> When you're installing barrier as a snap, don't install it via a UI! Install it via the terminal like so:
> 
> `snap install --devmode barrier`
> 
> This will circumvent all security sandboxing snap normally applies to an install, which prevents barrier from accessing the network socket properly. I'm sure there's a way to fix this when building the snap package, but as a workaround, this was good enough for me.

Installing the snap with `--devmode` is dangerous and defeats the whole idea behind snaps security; it should only be done for debugging and diagnosing issues. I use it daily with no issues myself, fwiw. [Here's a complete guide to debugging issues with snaps](https://snapcraft.io/docs/debug-snaps). Also, check that the `network` interface/permission is connected/granted, via `snap connections barrier`.

**Comment by iFreilicht** [comment]
@maxiberta It didn't really matter in my case, this was on a temporary machine with no important data, but you're right, it's not the right way. I tried uninstalling and reinstalling again, and I did check the permissions as you suggested, and this time it worked out of the box without any fiddling. Very strange, not sure what caused it to break the first time around.

**Comment by shridhar-hegde** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

Tried this and it works like a charm.
Thank You

**Comment by abhagsain** [comment]
I had the same issues. After an hour of searching Internet I got it working.  

My server is Windows 10 and Client is MacOS Catalina. 
Barrier was picking up the wrong IP Address which was my Ethernet IP Address.

![image](https://user-images.githubusercontent.com/36589645/110890719-93f8b000-8316-11eb-987d-b073582cc173.png)

So make sure you run `ipconfig` on the server, in my case it's **Windows 10** 
and see the correct IP Address Under **Wireless LAN adapter Wi-Fi** IPV4 address. 

![image](https://user-images.githubusercontent.com/36589645/110890917-ecc84880-8316-11eb-9e02-50a7e35cac38.png)

Make sure you give the same **Screen Name**  

In my case the name is **mac** (Windows 10 Screenshot)

![image](https://user-images.githubusercontent.com/36589645/110891136-652f0980-8317-11eb-897a-8eef8b51d562.png)

Mac OS Screenshot 

![image](https://user-images.githubusercontent.com/36589645/110891374-e1295180-8317-11eb-98dd-03c9520001e0.png)

I had problems if my Wifi is set to password protected (which is just my mobile hotspot). So to get around that I made it public and limited the connections to it. 

That's it. I hope it helps somebody :)

**Comment by ravihlb** [comment]
Had the same problem, the issue was that both computers had the almos exact same screen name (one being Title Cased, the other not), fixed by using different screen names.

**Comment by aboode95** [comment]
> > When you're installing barrier as a snap, don't install it via a UI! Install it via the terminal like so:
> > `snap install --devmode barrier`
> > This will circumvent all security sandboxing snap normally applies to an install, which prevents barrier from accessing the network socket properly. I'm sure there's a way to fix this when building the snap package, but as a workaround, this was good enough for me.
> 
> Installing the snap with `--devmode` is dangerous and defeats the whole idea behind snaps security; it should only be done for debugging and diagnosing issues. I use this snap daily with no issues myself, fwiw. [Here's a complete guide to debugging issues with snaps](https://snapcraft.io/docs/debug-snaps). Also, check that the `network` interface/permission is connected/granted, via `snap connections barrier`.

could you please explain how we can fix this without the devmode?

I cannot understand where to look for this network socket security issue in snap

**Comment by aboode95** [comment]
okay, I got it working by using the other ip address from the server barrier.

**Comment by juanmartin** [comment]
In my case, for some reason Windows disabled Network Discovery. I realized this because I couldn't share files over my LAN.
In Windows I went to the Network folder and I was prompted if I wanted to enable network discovery and file sharing for my (private) network and everything got fixed.

**Comment by Shisah** [comment]
Another cause of this issue is having a registered keystroke that points to a screen that does not exist, in my case i had a switch to screen to one i deleted.

**Comment by gnpaone** [comment]
> I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too.
> But, when I closed the SSL, it works.

How to disable/close SSL?

**Comment by Moh-Snoussi** [comment]
Windows Server to Ubuntu Client:
I solved the problem by getting the server IP from windows -> network status -> properties of the currently connected connection -> scroll down and copy the IPv4 address, this is our server address that need to be entered in the Ubuntu client section. 
the only problem that I face is windows mouse does not work well on ubuntu. but I can use shortcuts!!!

**Comment by sderose** [comment]
I think I've now tried everything above. I can't turn off the firewall on one machine, because company; however, Mac privacy/security panel says barrier is allowed through. Get nowhere with that machine as server; if I make a different Mac the server, and that one a client, it autoconfigs and claimed to be connected and running, but the client still says "barrier is starting", and nothing works. MacOS Big Sur all around.

**Comment by ShashaankHari** [comment]
Im connecting between 2 arch linux(garuda) devices, on one device barrier is running but on other on device its stuck at barrier is starting, tried all the steps above..

**Comment by Midnex** [comment]
Wish there was more info on how to resolve these issues. It should be as simple as adding a hostname or ip, and then showing what side of your computer that computer is on. I came here as this was highly recommended software. But can't even get it to work on a local network out of the box.

**Comment by franva** [comment]
> I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too. But, when I closed the SSL, it works.

this one works for me~! thanks ~!

**Comment by gnpaone** [comment]
> > I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too. But, when I closed the SSL, it works.
> 
> this one works for me~! thanks ~!

How did you do it? Any brief explanation or link please?

**Comment by franva** [comment]
> > > I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too. But, when I closed the SSL, it works.
> > 
> > 
> > this one works for me~! thanks ~!
> 
> How did you do it? Any brief explanation or link please?

From the menu, click "Change Configuration". You are welcome :)

**Comment by egemenertugrul** [comment]
Disabling SSL and 'Reload'ing from the server solved the issue for me.

**Comment by rafaeltgt** [comment]
It did work after disabling SSL in Barrier config

**Comment by martinszeltins** [comment]
> I just recently have the same issue.
> I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly.
> Hope this help.

Thank you @minhmoc I was having the same issue and adding the client manually to my server config made it work. I was banging my head against the wall why it wasn't working.

**Comment by ryancheta** [comment]
> I just recently have the same issue. I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly. Hope this help.

OK.... so after you create the new client in the server config, do you delete the original client that appeared? Do we reload just the server or both client and server?

**Comment by minhmoc** [comment]
I didn't delete the original client and just restart the server. I think it
doesn't master if you keep the original client or not.

Vào Th 7, 3 thg 12, 2022 vào lúc 01:44 Ryan Ancheta <
***@***.***> đã viết:

**Comment by karass2** [comment]
In my case the server side (Windows 10) of Barrier, which was properly setup and working fine, just stopped. Log showed "ERROR: ipc connection error, connection refused" message and none of the above has worked for me.

In Task Manager, under the Services tab, I found Barrier service, which was for some reason stopped. Right click on that service and choose Start. Problem solved.

**Comment by Amarel-Taylor-Scott** [comment]
Had a similar problem between Linux Mint and OSX.

Tried all the methods here and it still didn't work, but for some reason, it started working after I opened the "Network Settings" options and disabled then enabled both wireless and Wifi on my client computer (Linux Mint).

**Comment by zencore** [comment]
Another potential solution: Just dropping my solution incase anyone else has tried all of the others, without any luck.

It turns out I was running multiple instances of barrier on each computer (server and client). Check any tray icons you have to check that you are only running one. Or just reboot both to make sure 🙂👍

**Comment by robywoo** [comment]
I was running both on 2 Macs - client was stuck on "starting" So I finally stopped Barrier on the server and stopped it also on the client then restarted both and the client started working

**Comment by NitroHxC** [comment]
Thank you. Disabling SSL worked for me with Win10 as Server and Ubuntu 22.04 as Client.

**Comment by franva** [comment]
I got the same issue but my 2 OSs are:
Server: Ubuntu 20.04
Client: RPi BullEye 64Bit OS

Solution:
I disabled SSL + manually typed in my server ip, then restarted the Barrier.

**Comment by Michelangelo-Foresta** [comment]
> I had similar issue, but I did not look at the log to see what it said.
> 
> How I resolved it, is on the server machine select configure server and delete all machines that are in "Screens and links". Once I did that and reloaded barrier on both machines it was working. Hope this helps.

<3 you are the best.

**Comment by PJK2011** [comment]
It took me having to apply just about all of the suggestions in this thread and really paying attention to detail. What got it finally working for me was clicking to Save Configuration. I hadn't been doing that, and especially not noticing that  closing the GUI wasn't stopping Barrier and several copies of Barrier were running with different configurations, after closing them all out and rechecking all the menus and dialog boxes, I found one of them still had the SSH box checked. Once I cleared that, Barrier started running.

**Comment by VioletSnow08** [comment]
> I got the same problem. and after I drag the icon to add a new computer, it wouldn't work, too. But, when I closed the SSL, it works.

Thank you!!!

**Comment by fbrinker** [comment]
Thank you for all the hints. Input-Leap isn't an alternatîve for me yet without non-debug binaries. Barrier just works with a Win 11 Server and Arch Client after disabling SSL, but it I searched a while for the SSL option... It's behind Barrier -> Change Settings (F4). I always thought it's the SSL "Fingerprint" option at first... The Barrier Log was very helpful in seeing that it is still trying to use SSL :D

**Comment by deanrobin333** [comment]
I managed to get great help from all the advises above. I only needed to do one extra thing. which was to disable SSL. So this is now what worked for me. 

- go to settings and disable ssl on both
- then on the server machine select configure server and delete all machines that are in "Screens and links". Then click reload
- then adding new computer on the Configure Server, and name that computer with the same name appeared in client machine then reload and it works perfectly.

**Comment by JohnWilliston** [comment]
I had the same problem trying to get my iMac running macOS Monterey 12.7.3 to connect to my Windows PC running Windows 10 Pro x64. It seems like turning off SSL on the PC acting as a server _doesn't work_. I had to make sure SSL was enabled and then use the following commands to generate an SSL cert on the Windows machine:

```
cd %USERPROFILE%\AppData\Local\Barrier\SSL
"C:\Program Files\Git\mingw64\bin\openssl" req -x509 -nodes -days 365 -subj /CN=Barrier -newkey rsa:4096 -keyout Barrier.pem -out Barrier.pem
```

With that new certificate in place, restarting the server and restarting the client finally gave me the anticipated behavior. The client asked me to confirm the fingerprint of the newly generated cert, and all of a sudden it was working. Yay!

**Comment by dasboogles** [comment]
Ran into this just now, and I've collected the top issues that could cause this:  

- SSL is enabled, but no proper SSL configuration provided so it errors
- Hotkeys for machines that don't exist, clear them or update them
- Improper IP configuration being detected from your network interface

Any of the above errors can, or will, cause the "Barrier Service" to stop which will prevent your Barrier Server from going from "starting" -> "running". Once you've checked the above, go check your Services for the Barrier service and insure it is running.

**Comment by talk2emman** [comment]
Mine is not working even after disabling it

**Comment by leosanxyz** [comment]
> I just recently have the same issue. I make it work just by adding new computer on the Configure Server, and name that computer with the same name appeared in client machine (for example in your case the name should be set to Ryan-Ubuntu). Then reload and it works perfectly. Hope this help.

thanks! now is working as expected!
