### ISSUE TITLE
Cmake update causes error with barrier

### ISSUE THREAD

**Issue by kenny-w1** [debauchee/barrier#49]
### Operating Systems ###

Server: Artix

Client: Artix & Devuan

### Barrier Version ### 

snapshot, latest

### Steps to reproduce bug ###

Try to build barrier on arch-based distro with newest cmake from pacman package manager

qt5_use_modules is apparently deprecated but its back now? I don't know how to make this build now...

-- Full Barrier version string is '2.1.0-snapshot-snapshot.b1-773a0081'
-- Configuring directory /home/user/Compiles/Barrier-fresh/src/barrier/build/rpm
-- Configuring file barrier.spec
CMake Error at src/gui/CMakeLists.txt:25 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".

I'm having a hard time trying to figure out how to make this build now... :( 
QT_SELECT=5 / QT_SELECT=4 doesn't seem to have any effect...

**Comment by kenny-w1** [comment]
I think the problem is in the source-code of Barrier but maybe I'm wrong, I don't really know... 
This is really confusing :/ I can't find any answers to this anywhere.... ugh...

**Comment by xantoz** [comment]
Does the following patch resolve it (you might need to change SYNERGY to BARRIER in a few places): https://gitweb.gentoo.org/repo/gentoo.git/plain/x11-misc/synergy/files/synergy-1.9.1-qt-5.11.patch?id=5dd1f7a3908dec9ae6cf6773acd8ec3b33fc0b2c

**Comment by Tblue** [comment]
@xantoz, thanks -- the patch fixes the issue.

As a hotfix, I included the patch in the Arch Linux AUR package, see [0001-Handle-removal-of-cmake-macro-qt5_use_modules.patch](https://aur.archlinux.org/cgit/aur.git/plain/0001-Handle-removal-of-cmake-macro-qt5_use_modules.patch?h=barrier). Of course, credit for the patch goes to whoever created it for Gentoo. :-)

**Comment by johnny-mac** [comment]
Hey Tblue how do you make it skip the integrity check for the .patch file? It keeps wanting to do an integ check only when I include the .patch file, but even when I add 
md5sums=('SKIP')
sha256sums=('SKIP')
sha512sums=('SKIP')
it won't validate the integrity, even when I add the md5sums for the .patch file it still tells me:

-> Found 0001-Handle-removal-of-cmake-macro-qt5_use_modules.patch
==> ERROR: Integrity checks (md5) differ in size from the source array.

**Comment by Tblue** [comment]
@johnny-mac, as the error message says, *each* file in the `source` array needs to have a corresponding checksum (or the keyword `SKIP`) in the checksum arrays (`md5sums` etc.).

Try `makepkg -g >> PKGBUILD` to have the checksums generated automatically.

**Comment by walker0643** [comment]
Confirmation on fix and 3 weeks since activity. Closing for now but please reopen if I'm mistaken.

**Comment by walker0643** [comment]
I went ahead and added the patch. Seemed like a good idea ...
