### ISSUE TITLE
Server wont start anymore, unrecognized option `--enable-cypto'

### ISSUE THREAD

**Issue by haivala** [debauchee/barrier#497]
### Operating Systems ###

Server: Arch

Client: Windows 10

### Barrier Version ###

2.3.2-1

### Steps to reproduce bug ###
Updated and starting by `barriers --enable-crypto` does not work anymore
```
 ~  barriers --enable-cypto
barriers: unrecognized option `--enable-cypto'
Try `barriers --help' for more information.
```

### Other info ###

* Started happening after latest update
* I can run the GUI version and it works as usual
* Does this bug prevent you from using Barrier entirely? No

What to do?

**Comment by AdrianKoshka** [comment]
You made a typo, you put `--enable-cypto`, instead of `--enable-crypto`.

**Comment by shymega** [comment]
@haivala Can you please confirm that @AdrianKoshka's comment resolved the issue? I'd be grateful to know in case it did not resolve matters.
Cheers.

**Comment by haivala** [comment]
It did. Sorry for the issue.
