### ISSUE TITLE
Could you please tell what was the last Windows 32 supported version?

### ISSUE THREAD

**Issue by rin67630** [debauchee/barrier#499]
Many legacy systems / tablets are running 32 bit.
Synergy ran on them.
Could you please at least mention which was your last 32 bit compatible version?
Thank you.

**Comment by AdrianKoshka** [comment]
To my knowledge, you should still be able to build barrier for 32-bit windows systems, we just don't officially support 32-bit versions of windows.

**Comment by rin67630** [comment]
The installer refuses to install on a 32 bit tablet.

**Comment by AdrianKoshka** [comment]
We only support 64-bit windows for the installer.

**Comment by mirh** [comment]
The installer still seems to install just fine even on x86 tbh. 
You are only greeted with the hard reality once you try to run the program.

**Comment by shymega** [comment]
Yes, its true that the installer works fine on i386. My personal opinion is that we should begin supporting 32-bit again.. but I know there's a bit of opposition there. @debauchee/barrier-developers - thoughts? Reopening for further discussion.

**Comment by p12tic** [comment]
I think that support as many architectures as reasonably possible should be our goal.
