### ISSUE TITLE
Stuck on Barrier is starting

### ISSUE THREAD

**Issue by fieldengr2010** [debauchee/barrier#506]
I'm attempting to use Barrier between a Debian 10 and macOS Catalina (10.15.1) but keep getting the Barrier is starting message.

The Debian box is configured as the server and is ready and waiting.

The Mac is configured as the client with the server IP entered, but it doesn't go past the "is starting" point.

Any potential ideas or pointers to where this might be coming from at all?

The same happens to the Mac if I make it the server.

**Comment by fieldengr2010** [comment]
Found the source of the problem. Turns out I hadn't put the screen name in correctly and so it was refusing to talk to the Linux box.

**Comment by MisutaaAsriel** [comment]
> Found the source of the problem. Turns out I hadn't put the screen name in correctly and so it was refusing to talk to the Linux box.

Can I ask how you fixed this? I put in an invalid screen name by accident and now barrier just crashes in a loop.

I can't find any config files, and the generated config files have the correct screen name (but if you try launching barrier gui via the command line it shows that its being launched with `"--name", "Invalid Name"`.

I'd love to change it but I can't get into the config panel.

It seems to be storing the data in some kind of shared store somewhere? And loading it that way. But I have no idea where that is at.
