### ISSUE TITLE
Barrier can't reach far side of extended desktop display on client

### ISSUE THREAD

**Issue by BBlayne** [debauchee/barrier#513]
### Operating Systems ###

Server: Windows 10 1809 OS Build 17763.864

Client: Windows 10 1809 OS Build 17763.864

### Barrier Version ###

2.2.0-Release-18ac0fe4 (Both pcs)

### Steps to reproduce bug ###

1. Install and run Barrier on two windows clients.
2. Have the windows client have two screens, 2560x1600 resolution on both screens.
3. Have the windows server have one screen 2560x1440.
4. Attempt to bring the mouse from the server to the client and bring it to the farthest side of the client.
5. The mouse will stop about halfway through the second/extended desktop display of the client after successfully traversing the main screen of the client.

### Other info ###

* Problem occurred recently after several weeks of successful use, I don't recall this happening before.
* It's possible the client/servers are reversed, but currently I cannot reverse the client-server because otherwise barrier doesn't seem to work at all/i.e it doesn't connect.
* Bug is inconvenient and infringes workflow.

**Comment by techmehow** [comment]
I've noticed similar issues with other operating systems. Here's my example: 
Server: Ubuntu latest current build as of this post, Screen size: 1920x1080
Client: Windows 10 pro, latest build as of this post, Screen sizes: 
>>>>>Primary = Laptop resolution at 3840x2160, scaled to 250% for ease of readability of text. 
>>>>>Secondary = USBCtoVGA into 1920x1080P extended desktop. 

When i attempt to set the Primary display on windows to the 1920x1080P i get the same issue, mous only goes half across the laptop. 
When i switch the primary display to the laptop, then barrier functions properly. 

Perhaps try changing the resolution to 1440?

**Comment by BBlayne** [comment]
I unfortunately do not know. Since covid and Work From Home my work setup is different and so I can't say for sure. You can make it close and if I ever get the chance to test it out I'll let you know!

**Comment by shymega** [comment]
Its a bot, so I'm afraid it cannot reply. I have closed it for now anyway.

**Comment by raikoug** [comment]
I have the same issue,
Server PC with 1 screen, client Laptop with 2 screens, main screen is the external one. I can't reach the bottom of the laptop screen (the external is above the laptop, the server is on the left:

```
 _______________   _______________  
|      Server  |  |  Client EXT  |  
|              |  |              |  
|______________|  |______________|  
                  _______________  
                  | CL. Laptop   | 
                  |              |   
                  |______________|
```

If the laptop main screen is the external, i can't pass 3/4 of the screen going down, so I can't access the bar or any thing below there.
If I set Laptop screen as main I can reach anywhere.
It's just a comfort to have the main screen on external one, (a nice comfort)
All resolutions here are 1920*1980.

**Comment by smo-ddemerre** [comment]
I can confirm this issue is still an issue .
     _______________________________
    |  Server - Linux OS                 |
    | 2.4.0-release ac5a1bfd          |
    | 2560 x 1440                          |
    |_______________________________|
    
     _______________________________         _______________________________
    |  Client - Win - Screen 2         |       |  Client - Win - Screen 3         |
    |  2560 x 1440                          |       |  2560 x 1440              x          |
    |_______________________________|       |________________________x______|
                             _______________________________         
                            |  Client - Win - Screen 1         |                   ^
                            | Linux 2.4.0-release ac5a1bfd |                   this is about where the mouse gets.
                            |  1920 x 1080                          |                                            
                            |_______________________________|


when client screen 2 & 3 has resolution changed to 1920x1440 instead. the issue remains too.

**Comment by mariomeyrelles** [comment]
I confirm that this is still an issue. Using only Windows. If I switch who is the server, all works fine.

**Comment by smo-ddemerre** [comment]
Hello @shymega , @BBlayne , Regarding this issue (barrier cannot reach far side of windows client display),
Could this ticket - please - be reopened ? it has before been closed (because non-responsive by the original author), however I (and others) can confirm the issue is remaining (at least in version 2.4.0-release-3e0d758b).

greetings.

**Comment by shymega** [comment]
Barrier is no longer maintained. I am no longer involved with this project or issue.
