### ISSUE TITLE
how to install on Raspbian?

### ISSUE THREAD

**Issue by YantCaccia** [debauchee/barrier#520]
I mean I feel a stupid noob (I probably am) but I can't understand how to install it. What am I supposed to do? In the README it says "Your distro probably already has barrier packaged for it" okay so where to find it?
Very sorry for the dumb question, please help.

**Comment by JUANPARBELAEZ** [comment]
If it is Linux/Debian
$ sudo apt-get install barrier

**Comment by YantCaccia** [comment]
I feel more stupid than yesterday but okay! I thought i should pick a distro-specific package from somewhere manually.

Thanks a lot! Will close the (non)-issue. 
Have a nice day.
