### ISSUE TITLE
Cursor occasionally goes crazy on macOS 10.15 client

### ISSUE THREAD

**Issue by cthart** [debauchee/barrier#524]
### Operating Systems ###

Server: Ubuntu 19.10 eoan
Client: macOS 10.15.2 Catalina

### Barrier Version ###

Server is 2.3.2 from the jonathanf PPA
Client is 2.3.2

### Steps to reproduce bug ###

Fairly often (several times per hour it seems) the mouse pointer on the macOS client will "go crazy" when trying to move it, as if macOS and Barrier and both trying to reposition it. The mouse pointer hops around and is jittery. Sometimes clicking on the touchpad on the MacBook fixes it.

I have no idea how to reproduce this at present.

### Other info ###

It seems like the problem started to occur under macOS 10.15.2, maybe also under 10.15.1
Had the problem with server 2.3.1 too.

**Comment by cthart** [comment]
I `apt purge`d barrier, and then installed the snap version, but it only installed version 2.2.0
Are there any binary releases of 2.3.2 for any versions of Linux, preferably DEB packages?

**Comment by shaqesparon** [comment]
Same here... using Mac 10.15.2 when I move the cursor off-screen to next device I can still see it moving up and down on my mac screen while moving on my windows laptop.

Using Mac Mini late 2014? and Window laptop

**Comment by cthart** [comment]
It does still happen very occasionally, but a lot less frequently.
Previously it was several times a day, now it seems like it's once a week
or so.

**Comment by CodingAlbert** [comment]
I confirm it is still a problem on:

OS: MAcOS Big Sur
version 11.2.3
MacBook Pro (15-inch, 2018)
2,2 GHz 6 core Intel Core i7

Barrier: 2.3.2-Release-210c2b70

**Comment by cthart** [comment]
I haven't had this issue anymore in a long time.
Currently running 2.4.0 on macOS Monterey 12.6.5 as the client while the server is 2.4.0 on Ubuntu 22.04.2 LTS
