### ISSUE TITLE
Edge detection issues on multi-monitor client with different scaling

### ISSUE THREAD

**Issue by giammin** [debauchee/barrier#54]
this is a really old and know synergy bug

I hope that maybe here will be fixed because symless does not have any intention to fix it

https://github.com/symless/synergy-core/issues/5201

**Comment by walker0643** [comment]
Can you try 075d4f4758f86c49ef0b5257a2de076b1d7d4569 and report back? If you're not comfortable building from source you could wait for the next release, 2.2. Thanks!

**Comment by walker0643** [comment]
Please reopen if your problem persists after 2.2. Thanks :)

**Comment by giammin** [comment]
ok thanks!
