### ISSUE TITLE
Windows 10 drag and drop not working from client to server

### ISSUE THREAD

**Issue by Rings4** [debauchee/barrier#554]
### Operating Systems ###

Server: Windows 10 1709 x64

Client: Windows 10 1903 x64

### Barrier Version ###

2.3.2-snapshot-210c2b70

### Steps to reproduce bug ###

1. Drag .txt from server to client
2. Sends file as expected
3. Drag a different .txt from client to server
4. Nothing happens

### Other info ###

* Is there a way to work around it? No, not even copying normally on client and pasting on server works, or even vice versa
* Does this bug prevent you from using Barrier entirely? No, but it brings nothing new that Synergy didn't already have as a result.

It would be amazing if we could transfer files between server and client seamlessly so I wouldn't have to use Anydesk.

**Comment by the-wes** [comment]
@Rings4 Please provide log entries if possible. Thank you

**Comment by shymega** [comment]
Closing in favour of #855, duplicate.
