### ISSUE TITLE
altgr modifier

### ISSUE THREAD

**Issue by alvarogf97** [debauchee/barrier#56]
### Operating Systems ###

Server: Ubuntu 18.04

Client: Windows 10

altgr modifier do not work on client side

**Comment by dayne** [comment]
Have you tried on DEBUG2 and seeing what is detected when you hit altgr.

**Comment by alvarogf97** [comment]
it's work thanks, but I have the following warnings:
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi
I do not want to open GUI, but how can I init barrier with conf file from shell?

**Comment by alvarogf97** [comment]
./barriers --debug DEBUG --no-daemon --enable-crypto --no-tray

it's work. Thanks
