### ISSUE TITLE
Barrier, latest - Mar/2020 - UAC prompts 'break' connection for 5+ seconds

### ISSUE THREAD

**Issue by jaxjexjox** [debauchee/barrier#587]
### Operating Systems ###

Latest build.
Windows 7 -> Windows 10
UAC prompt will cause the mouse to simply no longer mouse over to the PC for 5+ seconds, it 'kicks me off' the remote connection and then it works again.

This is a consistent thing.

Is there a fix for this or just deal?

**Comment by DragoonAethis** [comment]
This is a known issue, see here: https://github.com/debauchee/barrier/issues/264 - workaround is to configure the Barrier client to always elevate (see last comment in that issue).

**Comment by p12tic** [comment]
Closing a per command by DragoonAethis. Thanks for raising the bug.

**Comment by Polyterative** [comment]
this works great
