### ISSUE TITLE
Barrier crashes on OS X El Capitan 10.11.6 - LSOpenURLsWithRole() failed

### ISSUE THREAD

**Issue by dblitt** [debauchee/barrier#601]
### Operating Systems ###

OS X El Capitan 10.11.6
iMac7,1 mid 2007

### Barrier Version ###

2.3.2-release

### Steps to reproduce bug ###

1. Open Barrier in the terminal with `open /Applications/Barrier.app`
2. Barrier crashes with the message `LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Barrier.app.`

### Other info ###

It has not ever worked on this machine.

**Comment by dblitt99** [comment]
Hmm - I did not see that 2.3.0 was marked as requiring macOS 10.12. The README should probably be updated to remove the reference to OS X and state the required macOS.

**Comment by tjangoW** [comment]
> 
> 
> Hmm - I did not see that 2.3.0 was marked as requiring macOS 10.12. I guess I am stuck with 2.1.0-release on OS X 10.11. The README should probably be updated to remove the reference to OS X and state the required macOS.

Thanks for the information. Where did you actually find out about the version requirement?
+1 to include required version of MacOS in the README
