### ISSUE TITLE
[Question] in Setting up Mac OS Catalina

### ISSUE THREAD

**Issue by scheung38** [debauchee/barrier#628]
Mac OS Catalina

Samsung ultra wide monitor with DisportPort x2 and 1x HDMI 

Don't understand how to configure Barrier. I have Server on one Mac

and Client on the other, and have been able control mouse from one machine to the other machine but cannot seem to share screen?

Sebastian

**Comment by idbrii** [comment]
Barrier (like Synergy before it) lets you share your mouse and keyboard between computers, but not video. For video, you'd want [Screen Sharing](https://support.apple.com/en-ca/guide/mac-help/mh14066/mac) (comes with Catalina).

**Comment by p12tic** [comment]
Closing per answer by @idbrii. Thanks!
