### ISSUE TITLE
Memory leak, 100% CPU usage on Linux when disconnecting client

### ISSUE THREAD

**Issue by bogdanwilli** [debauchee/barrier#637]
### Operating Systems ###

Server: Linux Manjaro 

Client: Windows 10 Version 1809 (OS Build 17763, 1098)

### Barrier Version ###

2.3.2-RELEASE-00000000

### Steps to reproduce bug ###

1. Connect server (linux) and client (windows)
2. Shut down the client (windows)
3. Bug occurs. CPU usage on the server (linux) increases to about 20% and memory usage increases until 100% is used up. Then the system becomes difficult to use

### Other info ###

* The error happens consistently
* process name that uses memory is "barriers"
* CPU usage increases when 100% memory is used.
* The error happens only when the client is actually shut down - It does not happen when it is just disconnected
* Workaround is: Restart barrier server application. Quit barrier application on server, this will bring the server back to normal
* the bug can be repeated without shutting down the server (linux) just by restarting barrier and reconnecting the client
* this is possibly related to bug #629 
* Does this bug prevent you from using Barrier entirely? No

**Comment by Modelmat** [comment]
Building from git fixed this for me; the latest release is from last year and I believe https://github.com/debauchee/barrier/pull/557 in February fixed this issue.

**Comment by nikolas-digitalBabylon** [comment]
I can confirm the bug with the snap package on Ubuntu 18.04LTS host and Windows 10 client.

**Comment by AfricaSaga** [comment]
Same here, CentOS 8 server / Win10Pro client
Memory usage went to 6+Gigs, crippled computer 
Had to restart barrier server

**Comment by brgavino** [comment]
After experiencing this issue consistently with a Win10 client and a Clear Linux Host, 2.3.3 client/server fixes this issue through multiple disconnects client/server restarts etc.

**Comment by p12tic** [comment]
2.3.3 fixed this issue.

Reopening and closing just that it does not look like a bot closed the issue for no reason.
