### ISSUE TITLE
Client not recognizing/writing special letters properly

### ISSUE THREAD

**Issue by ShadowBound221** [debauchee/barrier#644]
OS

Server and Client: Windows 10 Home

Barrier version

Server: 2.3.1-snapshot-58d8f020
Client:  2.3.1-snapshot-f1c57075

Bug

In Croatian there are 5 special letters (š,ž,č,ć,đ), š and ž work properly, but when writing on the client side the letters č,ć and đ are written as c and d.

**Comment by cultab** [comment]
Can also confirm on the following server/client with greek accented letters (άέίόύ) show up as (αειου)

Server: void gnu/linux
Client: windows 10

Server: 2.3.2-RELEASE-00000000
Client: 2.3.2-snapshot-210c2b70

**Comment by AndreasGrip** [comment]
I assume it's the same problem described in
https://github.com/debauchee/barrier/issues/217

**Comment by carlesoriol** [comment]
This is a blocking feature. You cannot use a virtual keyboard if misses basic characters accents are important but also |@#\...

Server: ubuntu 20.04
Client: ubuntu 20.04

Server: 2.3.2-Release-00000000
Client: 2.3.2-Release-00000000

**Comment by ThorstenWirth** [comment]
Workaround: https://github.com/debauchee/barrier/issues/134

i've used 
```
setxkbmap -device `xinput list | grep "Virtual core XTEST keyboard" | sed -e 's/.\+=\([0-9]\+\).\+/\1/'` de
```
Now it works fine

You'll might have to change the settings, if you're using dvorak - serch for `setxkbmap`

**Comment by eugenegff** [comment]
I think this is the same problem that was fixed in pull request https://github.com/debauchee/barrier/pull/910

**Comment by p12tic** [comment]
Agreed.
