### ISSUE TITLE
No continuous integration support on Windows

### ISSUE THREAD

**Issue by p12tic** [debauchee/barrier#66]
I think we should build barrier on Windows too. Appveyor CI supports this. Would you be interested in a PR?

**Comment by walker0643** [comment]
Definitely, @p12tic. I'll consider anything that helps with packaging and deployment.

**Comment by walker0643** [comment]
I now have it testing the Windows build, though I haven't done the installer portion yet. I'll get to that possibly tomorrow. I will, however, leave the OSX CI script to you :smile:

**Comment by walker0643** [comment]
Thanks to @p12tic we now have AppVeyor taking care of our Windows CI. Cheers!
