### ISSUE TITLE
Linux client ignores scrolls of less than 120 points

### ISSUE THREAD

**Issue by p12tic** [debauchee/barrier#67]
### Operating Systems

Client: Ubuntu Linux 16.04
Server: OSX 10.12 Sierra
### Barrier Version

Copied from https://github.com/symless/synergy-core/issues/5670.

### Steps to reproduce bug
1. Scroll slowly on the server
2. Observe that the client ignores the scroll
3. Observe that the log is filled with "WARNING: Wheel scroll delta (22) smaller than threshold (120)"

**Comment by walker0643** [comment]
https://github.com/debauchee/barrier/commit/f857354535271a7c36322be30a321d1ab041f859 should fix. Please reopen if it does not. Thanks :)

**Comment by dogweather** [comment]
Is this released in any version of the app? I just installed the latest in 1.x and am experiencing the problem.

**Comment by p12tic** [comment]
Hey, have you installed synergy or barrier? The fix is in barrier only (latest version 2.1.1), you can download it from here: https://github.com/debauchee/barrier/releases.

**Comment by dogweather** [comment]
@p12tic I've given up on this software - I've found that I get a much better experience using VNC from the Mac to Tiger VNC server.
