### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by unmanagedtn** [debauchee/barrier#681]
Can someone please explain to me what if anything is preventing someone from hijacking your machines if they get on your lan?

**Comment by simons-public** [comment]
@unmanagedtn Auto config is an option that you can turn off and point clients directly to the server. Additionally, clients have a `TrustedServers.txt` which has the fingerprints of authorized servers that you can manually specify. How secure your barrier setup is depends on how you configure it.

**Comment by unmanagedtn** [comment]
Just looking for documentation.
