### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by eligrey** [debauchee/barrier#687]
It may be possible to implement an Android app host for Barrier using accessibility APIs.

**Comment by shymega** [comment]
#189 already exists. You are welcome to post your suggestion there instead. Closing, as this is a duplicate issue.

**Comment by jayesh83** [comment]
> It may be possible to implement an Android app host for Barrier using accessibility APIs.

Yes it is indeed possible. we can inject click events using Accessibility service in Android. Looking forward to work on app for Barrier
