### ISSUE TITLE
Create different packages for GUI and non-GUI versions

### ISSUE THREAD

**Issue by AlwaysLivid** [debauchee/barrier#688]
Barrier's GUI version can be built with the `gui` build flag. That's convenient for operating systems like Gentoo Linux, where I can define whether I want the GUI with every update, but it gets a bit tougher when you need to start instances of Barrier in the background on Debian machines. I think that this would be a useful feature for both myself and other people as well.

Therefore, I'd like to request the creation of different packages for the GUI and the non-GUI version of Barrier.

**Comment by simons-public** [comment]
@AlwaysLivid You can still run barrier without the GUI if the GUI package is installed. The GUI is just a frontend that starts the `barrierc` client or `barriers` server processes.

**Comment by AlwaysLivid** [comment]
> The GUI is just a frontend that starts the `barrierc` client or `barriers` server processes.

Oh, I understand. I thought that you had to choose between `gui` and non-`gui` builds-- I tried to look into that myself, up to no avail. Thanks for the response!
