### ISSUE TITLE
press one key but show a line of this key

### ISSUE THREAD

**Issue by verigle** [debauchee/barrier#695]
### Operating Systems ###

Server: Windows 10

Client: Ubuntu 20.04

### Barrier Version ###
2.3.2
https://github.com/debauchee/barrier/

### Steps to reproduce bug ###

1. Click things.
2. Type things. t
3. Bug occurs. ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt
4. ... 
![image](https://user-images.githubusercontent.com/32769358/82870393-71053700-9f62-11ea-9e4c-6c6c4e4c9ad6.png)

### Other info ###

* When did the problem start to occur? Sometime 
* Is there a way to work around it?  Yes
* Does this bug prevent you from using Barrier entirely? Yes

Put anything else you can think of here.

**Comment by amerlyq** [comment]
Very similar to #269

**Comment by linaori** [comment]
Probably fixed by #679, see my issue opened about it: #617

**Comment by p12tic** [comment]
I believe this has been fixed in #679 in Barrier 2.3.3.
