### ISSUE TITLE
Need OSX zip files? [was MacReadme.txt]

### ISSUE THREAD

**Issue by aljorhythm** [debauchee/barrier#72]
link to configuration doesn't exist

**Comment by walker0643** [comment]
The link to the configuration guide is definitely invalid now. It is a Synergy artifact. More to the point, is the procedure given in the MacReadme.txt file still useful to anyone now that we have OSX installers? The Barrier project has not been providing zip files of mac binaries.

I'll leave this open for the mac community to comment on whether or not they require us to start offering these binaries zips like Synergy used to. Please include good reasons :)

**Comment by walker0643** [comment]
Inactive for over 2 months. Reopen if you think further discussion is needed.
