### ISSUE TITLE
Using over VPN

### ISSUE THREAD

**Issue by y20zhang-nokia** [debauchee/barrier#728]
### Operating Systems ###

Server/Client: Ubuntu 18.04 or Manjaro 20.01 or Windows 10

Is there any suggestion for using barrier over VPN? I lost control immediately after turning the VPN on.
I saw this [post](https://mrfrosti.com/2017/07/31/using-synergy-over-vpn/) about Synergy over VPN, but I am not sure how applicable it is.

**Comment by p12tic** [comment]
You need to still have routing to LAN available. I suspect your VPN solution redirects all network traffic through the VPN.

**Comment by fkieber** [comment]
I use successfully an ssh tunnel.
ssh -g -C -T -p 22 -L 24800:my_barrier_server_local_network_ip:24800  user@my_server_external_ip
On Windows you can use PuTTY.
