### ISSUE TITLE
[Feature request] Login with barrier on client computer

### ISSUE THREAD

**Issue by informathemusic** [debauchee/barrier#730]
### Operating Systems ###

Server: Debian buster

Client: Debian buster

### Barrier Version ###

Idk I just apt-ed it

### Feature request ###

Introduce some way to login on the client computer(s)

**Comment by shymega** [comment]
Please tell us the version in future - that would really help.. and also, the template should be used; its there for a reason Run `barrierc --version` to get the version.

Duplicate of #508, #540, and #297. Closing.
