### ISSUE TITLE
Feature Request: Mutual share option

### ISSUE THREAD

**Issue by adyanth** [debauchee/barrier#751]
Having a mutual share option would be of great assistance when there are multiple PCs and multiple peripherals (mouse needed for one, keyboard only for another), and we don't need to check which controls what before using it.

**Comment by Laneone** [comment]
+1 for having this feature can confirm things act flaky if you try to add multiple servers and clients to try and multiplex this feature on your own

**Comment by adyanth** [comment]
To start with, it can be as simple as, having the server running all the time, and we can provide the client on both PCs, so that two of them can use each other's peripherals.

**Comment by Laneone** [comment]
If someone can point me to the how this would be implemented I can try and submit a PR

**Comment by p12tic** [comment]
This

**Comment by p12tic** [comment]
I think that this is not easily possible in the current codebase. Basically we would need to change the basic design of how Barrier works. Unfortunately adding workarounds like multiple clients is not viable, as Barrier server currently assumes that there are no clients on the machine it's running on and implementing this would complicate whole codebase for little gain.
