### ISSUE TITLE
RFC: Wrap all platform interfaces in src/lib/platform and elsewhere

### ISSUE THREAD

**Issue by p12tic** [debauchee/barrier#76]
I propose wrapping the platform interfaces in src/lib/platform and other places with wrapper classes and then only allowing calling the methods of these classes. This would give us the following benefits:

 - Whole Barrier could be mocked, which would allow to easily write tests to prevent regressions
 - We could have wrapper implementation which would log all calls. This would allow much easier diagnostics of any platform-specific bugs that can't be easily reproduced by the developers. The user could just enable the logging functionality, reproduce the bug, collect logs and send them along the bug report. This way it would be possible to investigate the bugs, fix them and write regression tests all without having access to the reproduction environment, 

What do you think about this proposal?

**Comment by walker0643** [comment]
Discussed via IRC. Will review PRs as they come in.

**Comment by walker0643** [comment]
@p12tic are we still working on this?

**Comment by walker0643** [comment]
Closing this issue but I'm looking forward to the PRs.
