### ISSUE TITLE
cant lock mouse to specific pc/screen.

### ISSUE THREAD

**Issue by zalvasor** [debauchee/barrier#765]
### Operating Systems ###

Server: windows 10

Client: windows 10

### Barrier Version ###

1.9.π

### Steps to reproduce bug ###

1. Click things.
2. Type things.
3. Bug occurs.
4. ... 

### Other info ###

* When did the problem start to occur? When I start playing games.
* Is there a way to work around it? no really, it bothers my idea of this program
* Does this bug prevent you from using Barrier entirely? No

Im trying to start streaming and have dual pc. So i tried to have 1 mouse through both pc but i cant lock the mouse to specific screen because everytime i flick 180 in games my mouse goes over to the other pc/screen. Which i dont want to happen

**Comment by shymega** [comment]
Please fill in the template as defined. Thanks.
