### ISSUE TITLE
barrier - startup, what folder is the barrier file in Linux, start itself, save the IP server?

### ISSUE THREAD

**Issue by LearnRus88** [debauchee/barrier#767]
Hello, tell me in what folder is the barrier file in Linux? How to add a barrier to startup that it was launched when Linux started? How to make it start itself, without clicking on the Start button? How to save the IP server on the Client?

**Comment by huizichin** [comment]
just make it run command barrier on startup
that will start barrier

**Comment by yjfguhd** [comment]
Try _$HOME/.config/Debauchee/_.

**Comment by LegendModzYT** [comment]
Barrier works fine for me but I do want to have the Server IP save on exit and load back on startup so when I start my Raspberry Pi it automatically starts barrier and I have no need for using a separate mouse or keyboard. My server machine is on Windows by the way.
