### ISSUE TITLE
There are no mention of command-line options in the README.md.

### ISSUE THREAD

**Issue by aaltemara** [debauchee/barrier#787]
There are no mention of command-line options in the README.md.

I would like to understand what arguments the client supports, so I can auto-load a config file. But, at least in the Windows client, there is no --help or /? option.

Thanks for maintaining this. It helps me greatly!

Anthony

**Comment by simons-public** [comment]
@aaltemara There's documentation of the command line [on the wiki](https://github.com/debauchee/barrier/wiki/Command-Line)

**Comment by aaltemara** [comment]
I'm sorry. I see my mistake. I was trying to look for the command line
options for the barrier / barrier.exe binary, but I should be running the
barriers / barrierc binaries directly if I want to use a config file.

Thanks!!

Anthony
