### ISSUE TITLE
Wishlist: Roll a new release with some of the goodies that have landed on master since 2.3.2

### ISSUE THREAD

**Issue by cap10morgan** [debauchee/barrier#788]
Would love to get [this commit](https://github.com/debauchee/barrier/commit/3737ed634d6adfd19221b64c7f395dbc03789367) at least into a stable release of Barrier. The current latest stable release is pretty hard on the eyes on HiDPI macOS.

Thanks!

**Comment by shymega** [comment]
I'm preparing a release.

**Comment by shymega** [comment]
Pleased to announce a release has been made. I'm not sure if it'll work -- this is my first time doing a release with Azure Pipelines! - but please let me know of any issues :smiley:
