### ISSUE TITLE
"This app can't run on your PC" on installation of 2.3.3

### ISSUE THREAD

**Issue by NostraDavid** [debauchee/barrier#795]
### Operating Systems ###

This app can't run on your PC

Client: Win 10 Version 2004 (OS Build 19041.329)

### Barrier Version ###

2.3.3

### Steps to reproduce bug ###

**READ ME, DELETE ME**: Try to be succinct. If your bug is intermittent, try and describe what you're doing when it happens most.

1. Download https://github.com/debauchee/barrier/releases/download/v2.3.3/BarrierSetup-2.3.3.exe
2. Run it and click through all the "are you sure" menus.
3. Get a "This app can't run on your PC" notification.

I uninstalled v2.3.2, removed any and all related folders, tried to install 2.3.3 and got this error ;_;

**Comment by NostraDavid** [comment]
2.3.2 installs just fine.

**Comment by Piero512** [comment]
I have the same exact issue, windows complains that this app can't run on your PC. 

I also tried the macOS build, and no dice either.

**Comment by cthart** [comment]
Same here. I get "image not recognised" trying to open the .dmg

Seems like there are some corrupt uploads.

**Comment by shymega** [comment]
Looking into it. Apologies!

**Comment by shymega** [comment]
Yeah, its because Azure zips them up.. and I didn't extract it. I'm just uploading them now.. Let me know if that works.

**Comment by NostraDavid** [comment]
`BarrierSetup-2.3.3-release.exe` has the same problem.

**Comment by Chris-Grundy** [comment]
> `BarrierSetup-2.3.3-release.exe` has the same problem.

I confirm this

**Comment by shymega** [comment]
Damn.. this is odd. OK, I'm just uploading the "real" EXE now. Hopefully that should work. The problem is that Azure Pipelines _appears_ to zip everything, and then present it as a .exe. Which as you can see, has caused some confusion!

**Comment by shymega** [comment]
OK, should be an EXE now. Apologies all, this has taken longer than it should have!

**Comment by shymega** [comment]
At some point, it would be great to have Azure do the releases..

**Comment by NostraDavid** [comment]
I can confirm everything works as intended! Thanks for the fast response!

**Comment by shymega** [comment]
Excellent. Sorry for the issues! Note taken.

**Comment by p6002** [comment]
Any fix for it?

**Comment by shymega** [comment]
> Any fix for it?

I said, it is fixed. In this repo. But I'm not part of Barrier anymore, so I'm gonna go ahead and unsubscribe from this issue...
