### ISSUE TITLE
macOS image for 2.3.3 can't be opened

### ISSUE THREAD

**Issue by cthart** [debauchee/barrier#796]
Getting "image not recognised" when trying to open 2.3.3 on macOS.

**Comment by shymega** [comment]
Damnit. Something must have gone wrong with the build... I'll look into it.

**Comment by cthart** [comment]
Seems to be affecting both Windows and macOS users, strangely enough -- though there was one person who got the Windows install to work.

**Comment by shymega** [comment]
Yeah, its because Azure zips them up.. and I didn't extract it. I'm just uploading them now.. Let me know if that works.

**Comment by shymega** [comment]
Any other macOS users, would be grateful for a test. I believe it should work now I've extracted the actual DMG.

**Comment by SeekingMeaning** [comment]
Latest DMG works! Thanks!

**Comment by shymega** [comment]
Glad to hear it.

**Comment by cthart** [comment]
I should've mentioned that the new upload worked for me too -- hence I closed the issue.
