### ISSUE TITLE
building on win 10

### ISSUE THREAD

**Issue by miramardesign** [debauchee/barrier#80]
### Operating Systems ###

Win 10

### Barrier Version ###

1.9.
### Steps to reproduce bug ###

git clone -> looks for exe --> trys build installer  -->

> o build a 64-bit Windows installer:
>  - set Q_BUILD_TYPE=Release in build_env.bat
>  - also set other environmental overrides necessary for your build environment
>  - run clean_build.bat to build Barrier and verify that it succeeds
>  - re-run this script to create the installation package
> 

creates build_env.bat with setting --> 

clean_build.bat
Bonjour: C:\Program Files\Bonjour SDK
Qt: C:\Qt\5.6.3\msvc2015_64
'cmake' is not recognized as an internal or external command,
operable program or batch file.
Build failed

--> looks for exe online.

**Comment by p12tic** [comment]
Do you have CMake installed?

**Comment by miramardesign** [comment]
no. basically i need documentation on that .   googled. but a lot of sources.

**Comment by miramardesign** [comment]
https://cmake.org/download/ ?

**Comment by miramardesign** [comment]
C:\Users\hazz\Documents\barrier>clean_build.bat
Bonjour: C:\Program Files\Bonjour SDK
Qt: C:\Qt\5.6.3\msvc2015_64
CMake Error at CMakeLists.txt:19 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Users/hazz/Documents/barrier/build/CMakeFiles/CMakeOutput.log".
Build failed

C:\Users\hazz\Documents\barrier>

**Comment by johannesstung** [comment]
@miramardesign When installing Visual Studio make sure 'Desktop development with C++' is chosen under 'Workloads' tab.

**Comment by walker0643** [comment]
Inactive for over a month. Please reopen as a documentation request if you still feel that our docs are lacking. Thanks!
