### ISSUE TITLE
gmock and gtest missing 

### ISSUE THREAD

**Issue by autotoxicus** [debauchee/barrier#805]
### Operating Systems ###
Raspian

### Barrier Version ###
2.3.3

### Steps to reproduce bug ###
I'm trying to compile your program on my RaspberryPi and `cmake .` is giving me two error messages.
```
Cannot Find Source File:
../../ext/gmock/src/gmock-all.cc
```
and
```
Cannot Find Source File:
../../ext/gtest/src/gtest-all.cc
```
Indeed, the folders gmock and gtest are empty in the source.

### Other information ###
I'm following this information for compiling https://github.com/debauchee/barrier/issues/41#issuecomment-392900982 , but the command for git clone is giving me an error message.
```
Permission denied (public key).
fatal: Could not read from remote repository.

Please make sure you have correct access rights and the repository exists.
```
So I did simply clone the source as I have done it every time so far with `git clone 'web adress of repository'`.  Perhaps this could be the reason for this problem?

**Comment by p12tic** [comment]
You need to run `git submodule init` and `git submodule update` before compiling.

**Comment by autotoxicus** [comment]
Thanks you for the quick help. I will give that a try tomorrow and report back afterwards.

Are btw different versions compatible with each other? I would then have 2.3.3 on my RaspberryPi, but my Desktop and Notebook have 2.3.2 from the package manager.

**Comment by autotoxicus** [comment]
I've got it working! Thanks a lot for your help and this great tool.

And to answer my own question from the post before: 
The two different versions are working fine together.

**Comment by mariolpantunes** [comment]
I have the same error.
The solution is not valid since I am trying to compile the release tarball, and there is no git folder.
