### ISSUE TITLE
Barrierc.exe blocks screen powersave

### ISSUE THREAD

**Issue by mastro-pi** [debauchee/barrier#817]
### Operating Systems ###

Server: Ubuntu Linux

Client:  Windows 10

it seems that barrierc.exe somehow interferes with the power save function of my screen.
I can't get my client screen to go off since I installed barrier 2.3.3. Windows system sleep diagnostics says this :-)

**Comment by shymega** [comment]
Any luck with 2.3.2? Might be a regression.

**Comment by mastro-pi** [comment]
nope. Tried even that version with no luck.

**Comment by shymega** [comment]
OK, thanks for letting me know :+1:

**Comment by mavack** [comment]
Also seeing this 
Server: windows 10
Client : windows 10

Stopping the connection on both allows them to sleep. Haven't worked through all the combinations of running and stopped.

**Comment by Onepamopa** [comment]
That's why I'm using "black" screensavers ;) at least a tempfix.

**Comment by himdel** [comment]
The server has a "Synchronize screen savers" option, have you trying turning it off?

**Comment by mastro-pi** [comment]
That did the trick! Turning off that setting let the screensaver doing his job! :-)
Many thanks himdel

**Comment by FFS-GmbH** [comment]
This solved my same issue with barrier 2.3.4 (Client+Server are Win 10 Pro).
