### ISSUE TITLE
Wiki page is out of date

### ISSUE THREAD

**Issue by ctsrc** [debauchee/barrier#819]
Just a heads up, https://github.com/debauchee/barrier/wiki lists the current version of Barrier as 2.3.2, and the download links are also for 2.3.2, rather than listing the current version as 2.3.3 and linking to downloads for 2.3.3.

**Comment by shymega** [comment]
Fixed in commit 1bf9eec4dc1112c5afb647e777a321af230b5a6c on the Barrier wiki repo.
