### ISSUE TITLE
how to switch ip address？

### ISSUE THREAD

**Issue by lyolve** [debauchee/barrier#876]
I use zerotier to create a virtual local area network，and the ip is 10.147.17.x，there is correct ip address shown on the interface of Barrier，but only 192.168.1.x is bolded，can i switch communication address from 192.168.1.x to 10.147.17.x ？

---
English is not my mother tongue，sorry~

**Comment by shymega** [comment]
You mean the bind address?

**Comment by lyolve** [comment]
Thank you for your reply.
I've worked it out.
It seems that I misunderstood the meaning of the bold fonts.
![image](https://user-images.githubusercontent.com/43743367/93838571-acb7cf80-fcbc-11ea-910a-d281393f8fb2.png)
