### ISSUE TITLE
Decide on documentation generation framework for end-user docs.

### ISSUE THREAD

**Issue by AdrianKoshka** [debauchee/barrier#88]
Going to go out on a limb and say we're just going to host docs that aren't shipped with `barrier` itself via github pages. If anyone here has any preference to a particular framework, speak up now. Some examples:

- [x] [MkDocs](www.mkdocs.org)
- [Docusaurus](https://docusaurus.io)
- [Slate](https://github.com/lord/slate)

**Comment by CrafterLaughter** [comment]
no preference.  just glad you're taking up it as it will help a lot.  cheers!
