### ISSUE TITLE
/*

### ISSUE THREAD

**Issue by AlexisWalravens** [debauchee/barrier#882]
Server: Windows
Client: Mac OS

They are both real machines.

I use my windows mouse on my mac but with a real mac keyboard.

Alt |  Ctrl | Shift | Super (on real keyboard) + click (Windows mouse) doesn't work.
Alt |  Ctrl | Shift | Super (on Windows keyboard) + click (Windows mouse) Works.

**Comment by shymega** [comment]
Thanks for the report, you need to follow the template to be honest. Its there for a reason. And can you set the title correctly? These little steps make all the difference...

**Comment by AlexisWalravens** [comment]
Oh sorry, my 2yo reposted this issue god knows how.
Here is the original: [https://github.com/debauchee/barrier/issues/881](https://github.com/debauchee/barrier/issues/881)

**Comment by shymega** [comment]
Thanks for editing it.
