### ISSUE TITLE
2.1.2 for mac (dmg)?

### ISSUE THREAD

**Issue by brianmorton** [debauchee/barrier#89]
![image](https://user-images.githubusercontent.com/1434096/42232695-17999ac0-7ea4-11e8-9a41-f51e00b7b339.png)

Will there be a binary for macOS for 2.1.2 (or any releases going forward)?

**Comment by p12tic** [comment]
Hi, these are source-only releases for testing. Full binaries will be provided once developers are sure that the quality is good for use by general public :-)

**Comment by brianmorton** [comment]
Thanks. I am trying to maintain this for homebrew. Sounds like if there is no dmg released then it is meant as a dev-only build?

**Comment by p12tic** [comment]
I believe that's right. @walker0643 could you correct me if I'm wrong?

**Comment by AdrianKoshka** [comment]
It's a source-only release for me specifically, for my testing of building a flatpak. It solved a hack I had to use.
