### ISSUE TITLE
Windows 7 and Ubuntu 20.04 no longer working after windows sleep

### ISSUE THREAD

**Issue by dookei** [debauchee/barrier#909]
Hi there,
My barrier worked for a day! :-)
Both machines are on the same local network and both can ping each other. 
I disabled already all the firewalls to see if the issue was related to the firewall. No luck neither. 
The weird thing is that this worked already before. The only thing I have done was to put the windows machine to sleep for the night. In the next morning no longer connects to the server. 
I also tried to set the server on the windows machine. Reinstall  Barrier on both machines ...etc... nothing seams to work no more. 
My  Barrier version on both machines is  2.3.2.
Any idea what might be?

Greetings

**Comment by mcnaveen** [comment]
Can you post the log? Me too faced the same kinda issue. #737

**Comment by dookei** [comment]
Hi @mcnaveen ,
thanks for your reply. The solution that you proposed also worked for me ?
**sudo iptables -I INPUT -p tcp --dport 24800 --syn -j ACCEPT**
I believe that when I activated the vpn  kill switch it closed some ports for me. I now added this command to the startup script with barrier. Many thanks !

**Comment by mcnaveen** [comment]
You're Welcome 🙂

**Comment by mcnaveen** [comment]
Kindly close this issue buddy
