### ISSUE TITLE
Barrier 2.3.3 source release is missing gmock and gtest

### ISSUE THREAD

**Issue by J-M0** [debauchee/barrier#911]
The source code download for [barrier-2.3.3-release.tar.gz](https://github.com/debauchee/barrier/releases/download/v2.3.3/barrier-2.3.3-release.tar.gz) is missing the source files in `etx/gmock` and `ext/gtest`. This causes the build to fail.

Also, the source archive extracts into the current directory which is undesirable.

**Comment by shymega** [comment]
On it.

**Comment by shymega** [comment]
Fixed.

**Comment by J-M0** [comment]
Thanks!
