### ISSUE TITLE
"Barrier is starting" Lubuntu

### ISSUE THREAD

**Issue by patrickfeeney03** [debauchee/barrier#912]
**Describe the bug**

**To Reproduce**
Just installed it through snap.

Just click on Start in the client.

**Expected behavior**
Its expected to say started, but just says is starting.

**Desktop (please complete the following information):**

 - OS: [Lubuntu]
- Barrier version 2.3.3-release-bbd1accb

Im trying to connect using Windows 10 as a server 2004.

**Comment by pablodiegoss** [comment]
I'm using Lubuntu 19.10 client with a Windows 10 as server, installed it through Snap also. It is working fine here with that same release that you posted, I've just updated to it.
I'm guessing that it might be your server configuration. Did you add your client to the server configuration correctly?
