### ISSUE TITLE
Ubutnu installation - Package 'libqt4-dev' has no installation candidate

### ISSUE THREAD

**Issue by phanijsp** [debauchee/barrier#935]
Can't install barrier in ubuntu 20. The package, **libqt4-dev** was _dropped_ from Ubuntu after 19.10.

1. Open terminal
2. run '**sudo apt install libqt4-dev**'

- OS: **Ubuntu 20.04 focal**
- Barrier version  2.3.3

**Comment by protobruce** [comment]
Hi I'm also having this issue.

**Comment by protobruce** [comment]
`sudo apt install barrier` ended up working on ubuntu 20.10.

**Comment by giobyte8** [comment]
I had same issue with ubuntu 20.04 LTS while compiling from source, just remove `libqt4-dev` from list of installed packages and it worked, it seems like `libqt4-dev` is not really a requirement? 🤔

**Comment by adam4235** [comment]
> I had same issue with ubuntu 20.04 LTS while compiling from source, just remove `libqt4-dev` from list of installed packages and it worked, it seems like `libqt4-dev` is not really a requirement? 🤔

Same with me, the instructions here say I need libqt4-dev:
https://github.com/debauchee/barrier/wiki/Building-on-Linux

But when I removed that package from the list then the build worked.  Do those instructions need to be updated?  Is there another package I needed instead that I happened to already have?
