### ISSUE TITLE
Logging issues

### ISSUE THREAD

**Issue by Every0ne** [debauchee/barrier#96]
I run barrierc with `--log /dev/null` option, however my log files still get littered with thousands of lines of

```
timestamp machine Barrier[3044]: 2.1.0-RELEASE: [2018-07-16T22:20:58] NOTE: connecting to 'servername': 172.16.0.X:24800
timestamp machine Barrier[3044]: 2.1.0-RELEASE: [2018-07-16T22:20:57] WARNING: failed to connect to server: Timed `out`

```
whenever the server is not running (and most often it isn't). Is there a way to truly disable logging or reduce verbocity to critical errors only?

**Comment by AdrianKoshka** [comment]
I think you're confusing logging to a file with the logging to (what I assume is) `stderr`.

**Comment by Every0ne** [comment]
I'm no *nix expert, but even when run with `2>/dev/null 1>/dev/null` barrierc still outputs to system-owned log files. What's the reason for `--log` option then? What I see is that it doesn't do anything at all, no files are created nor written to.

**Comment by W4RH4WK** [comment]
As I understand it, log output is always written to the console. The `--log` causes it to *also* write the output to the given file.
