### ISSUE TITLE
Can support for android devices added to barrier ?

### ISSUE THREAD

**Issue by bharathraja** [debauchee/barrier#991]
Android developers working on real devices from PC, laptop switch frequently between PC and android. It would be helpful if android support can be added to barrier software.

**Comment by YandiBanyuKarimaWaly** [comment]
> Android developers working on real devices from PC, laptop switch frequently between PC and android. It would be helpful if android support can be added to barrier software.

I think there is a better solution for that. Why don't you try [scrcpy](https://github.com/Genymobile/scrcpy)?

**Comment by bharathraja** [comment]
That simple solution. Thanks

**Comment by AnshulKathet** [comment]
for scrcpy one has to use the usb connector cable. can someone create an app for android.

**Comment by pguimier** [comment]
It can alsi be done with wifi, but scrcpy need developper mode
